package localization

var Persian = map[string]interface{}{
	"firstName":       "نام",
	"lastName":        "نام خانوادگی",
	"phone":           "شماره تماس",
	"email":           "ایمیل",
	"password":        "رمز عبور",
	"confirmPassword": "تأیید رمز عبور",
	"name":            "نام",
	"address":         "آدرس",
	"fields": map[string]interface{}{
		"phoneNumber": "شماره تماس",
		"otp":         "رمز یکبار مصرف",
		"code":        "کد",
	},
	"errors": map[string]interface{}{
		"invalid_request_body":   "بدنه درخواست نامعتبر است.",
		"generic":                "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                "`{0}` باید عدد باشد.",
		"fileRequired":           "وارد کردن فایل اجباری است.",
		"minimumLength":          "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":      "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":      "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":         "باید حتما دارای عدد باشد.",
		"containsSpecialChar":    "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":      "قبلا با این {0} ثبت نام کرده است.",
		"required":               "بخش {0} باید کامل شود.",
		"e164":                   "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                "رمز عبور و {0} مطابقت ندارند.",
		"eq":                     "مقدار {0 باید درست باشد}",
		"Expired":                "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":                "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":          "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials": "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":       "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":       "در توکن ورود شما اشکالی وجود دارد.",
		"UNAUTHORIZED":           "ابتدا باید وارد شوید.",
		"INVALID_TOKEN":          "توکن نامعتبر یا منقضی شده است.",
		"TOKEN_EXPIRED":          "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"MISSING_TOKEN":          "توکن احراز هویت وجود ندارد.",
		"FORBIDDEN":              "اجازه دسترسی وجود ندارد.",
		"unauthorized":           "ابتدا باید وارد شوید.",
		"notExist":               "این {0} وجود ندارد.",
		"alreadyExist":           "این {0} قبلا وجود داشته است.",
		"notFound":               "این {0} پیدا نشد.",
		"notVerified":            "باید ابتدا حساب خود را فعال کنید.",
		"forbiddenError":         "اجازه دسترسی به این {0} وجود ندارد.",
		"forbiddenStatus":        "اجازه انجام این کار را در این وضعیت ندارید.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":      "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification": "شماره شما با موفقیت تایید شد.",
		"login":             "شما با موفقیت وارد شدید.",
		"updateContactInfo": "اطلاعات تماس با موفقیت به روز شد.",
		"deleteContactInfo": "اطلاعات تماس با موفقیت حذف شد.",
		"changePassword":    "رمز عبور با موفقیت تغییر کرد.",
		"forgotPassword":    "لطفا پیامک های خود را بررسی کنید تا تلفن خود را تایید نمایید .",
		"resetPassword":     "گذرواژه با موفقیت تغییر کرد.",
		"refreshToken":      "نشست شما با موفقیت تمدید شد.",
		"completeRegister":  "اطلاعات تکمیلی ثبت نام با موفقیت انجام شد.",
		"updateProfile":     "پروفایل شما با موفقیت به روزرسانی شد.",
	},
}
