package localization

var Persian = map[string]interface{}{
	"firstName":       "نام",
	"lastName":        "نام خانوادگی",
	"phone":           "شماره تماس",
	"email":           "ایمیل",
	"password":        "رمز عبور",
	"confirmPassword": "تأیید رمز عبور",
	"name":            "نام",
	"address":         "آدرس",
	"fields": map[string]interface{}{
		"phoneNumber": "شماره تماس",
		"otp":         "رمز یکبار مصرف",
		"code":        "کد",
	},

	"ERR_EMPTY_IMAGE":        "تصویر نمی‌تواند خالی باشد",
	"ERR_OCR_MARSHAL":        "آماده‌سازی درخواست OCR ناموفق بود.",
	"ERR_OCR_CREATE_REQ":     "ایجاد درخواست HTTP برای OCR ناموفق بود.",
	"ERR_OCR_SEND_REQ":       "ارسال درخواست OCR ناموفق بود.",
	"ERR_OCR_READ_RESP":      "خواندن پاسخ OCR ناموفق بود.",
	"ERR_OCR_PARSE_RESP":     "پردازش پاسخ OCR ناموفق بود.",
	"ERR_OCR_NO_CHOICES":     "هیچ پاسخی از سرویس OCR دریافت نشد.",
	"ERR_OCR_DECODE_CONTENT": "تبدیل محتوای OCR به فرمت مورد انتظار ناموفق بود.",
	"ERR_OCR_SERVICE_ERROR":  "سرویس OCR با خطا پاسخ داد: {0}",
	"validation": map[string]interface{}{
		"missing_photo":              "لطفاً فایل 'photo' را ارائه دهید",
		"missing_video":              "لطفاً فایل 'video' را ارائه دهید",
		"missing_image":              "لطفاً فایل 'image' را ارائه دهید",
		"invalid_profile_id":         "شناسه پروفایل نامعتبر است",
		"invalid_ticket_id":          "شناسه تیکت نامعتبر است",
		"invalid_file_extension":     "پسوند فایل الزامی است",
		"invalid_request_parameters": "پارامترهای درخواست نامعتبر است",
	},
	"errors": map[string]interface{}{
		"invalid_request_body":      "بدنه درخواست نامعتبر است.",
		"generic":                   "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                   "`{0}` باید عدد باشد.",
		"fileRequired":              "وارد کردن فایل اجباری است.",
		"minimumLength":             "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":         "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":         "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":            "باید حتما دارای عدد باشد.",
		"containsSpecialChar":       "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":         "قبلا با این {0} ثبت نام کرده است.",
		"required":                  "بخش {0} باید کامل شود.",
		"e164":                      "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                   "رمز عبور و {0} مطابقت ندارند.",
		"eq":                        "مقدار {0 باید درست باشد}",
		"Expired":                   "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":                   "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":             "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials":    "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":          "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":          "در توکن ورود شما اشکالی وجود دارد.",
		"UNAUTHORIZED":              "ابتدا باید وارد شوید.",
		"INVALID_TOKEN":             "توکن نامعتبر یا منقضی شده است.",
		"TOKEN_EXPIRED":             "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"MISSING_TOKEN":             "توکن احراز هویت وجود ندارد.",
		"FORBIDDEN":                 "اجازه دسترسی وجود ندارد.",
		"unauthorized":              "ابتدا باید وارد شوید.",
		"notExist":                  "این {0} وجود ندارد.",
		"alreadyExist":              "این {0} قبلا وجود داشته است.",
		"notFound":                  "این {0} پیدا نشد.",
		"notVerified":               "باید ابتدا حساب خود را فعال کنید.",
		"forbiddenError":            "اجازه دسترسی به این {0} وجود ندارد.",
		"forbiddenStatus":           "اجازه انجام این کار را در این وضعیت ندارید.",
		"facePhotoEmpty":            "تصویر نمی‌تواند خالی باشد",
		"faceVideoEmpty":            "ویدیو نمی‌تواند خالی باشد",
		"faceImageEmpty":            "تصویر نمی‌تواند خالی باشد",
		"faceVerificationSuccess":   "تأیید چهره با موفقیت انجام شد",
		"faceVerificationFailure":   "تأیید چهره ناموفق بود",
		"apiKeyActiveExists":        "یک کلید API فعال برای این پروفایل وجود دارد.",
		"apiKeyProfileNotFound":     "پروفایل با این شناسه یافت نشد.",
		"apiKeyRevoked":             "این کلید API باطل شده است.",
		"apiKeyInvalidFormat":       "فرمت کلید API نامعتبر است.",
		"apiKeyAuthFailed":          "احراز هویت ناموفق بود.",
		"file_error":                "پردازش فایل ناموفق بود",
		"file_read_error":           "خواندن فایل ناموفق بود",
		"internal_validation_error": "خطای اعتبارسنجی داخلی",
		"access_denied_profile":     "دسترسی به این پروفایل رد شد",
		"user_not_found":            "کاربر یافت نشد",
		"email_already_exists":      "ایمیل قبلاً وجود دارد",
		"phone_already_exists":      "شماره تلفن قبلاً وجود دارد",
		"failed_get_profile":        "دریافت پروفایل کاربر ناموفق بود",
		"failed_update_profile":     "به‌روزرسانی پروفایل ناموفق بود",
		"failed_retrieve_summary":   "دریافت خلاصه استفاده ناموفق بود",
	},
	"successMessage": map[string]interface{}{
		"userRegister":      "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification": "کد OTP با موفقیت ارسال شد.",
		"login":             "شما با موفقیت وارد شدید.",
		"updateContactInfo": "اطلاعات تماس با موفقیت به روز شد.",
		"deleteContactInfo": "اطلاعات تماس با موفقیت حذف شد.",
		"changePassword":    "رمز عبور با موفقیت تغییر کرد.",
		"forgotPassword":    "لطفا پیامک های خود را بررسی کنید تا تلفن خود را تایید نمایید .",
		"resetPassword":     "گذرواژه با موفقیت تغییر کرد.",
		"refreshToken":      "نشست شما با موفقیت تمدید شد.",
		"completeRegister":  "اطلاعات تکمیلی ثبت نام با موفقیت انجام شد.",
		"updateProfile":     "پروفایل شما با موفقیت به روزرسانی شد.",
		"apiKeyGenerated": "کلید API با موفقیت ایجاد شد",
		"apiKeyRegenerated":     "کلید API با موفقیت بازسازی شد",
		"documentSaved":         "سند با موفقیت ذخیره شد",
		"profileSubmitted":      "پروفایل با موفقیت ارسال شد",
		"profileApproved":       "پروفایل با موفقیت تایید شد",
		"profileRejected":       "پروفایل با موفقیت رد شد",
		"profileDeleted":        "پروفایل با موفقیت حذف شد",
		"ticketsFetched":        "تیکت‌ها با موفقیت دریافت شدند",
		"walletSummaryFetched":  "خلاصه کیف پول با موفقیت دریافت شد",
		"transactionsFetched":   "تراکنش‌ها با موفقیت دریافت شدند",
		"depositSuccessful":     "واریز با موفقیت انجام شد",
		"profileUpdatedSuccess": "پروفایل با موفقیت به‌روزرسانی شد",
	},
	"apikey": map[string]interface{}{
		"activeKeyExists":  "یک کلید API فعال برای این شناسه پروفایل وجود دارد",
		"useRegenerate":    "برای جایگزینی کلید خود از /regenerate استفاده کنید.",
		"invalidProfileID": "شناسه پروفایل نامعتبر است"},
	"ERR_TRIAL_EXCEEDED": "تعداد آزمایش‌های دمو تمام شده است. برای ادامه لطفاً ثبت‌نام کنید.",
}
