services:
  postgres:
    image: postgres
    container_name: barbod-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: barbod-redis
    restart: always
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --replica-read-only no # for data persistance
    healthcheck:  # for container health monitoring
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  minio:
    image: minio/minio
    container_name: barbod-minio
    restart: always
    ports:
      - "9000:${MINIO_PORT}"
      - "9001:${MINIO_PANEL_PORT}"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: barbod-jaeger
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686/api/traces"]
      interval: 10s
      timeout: 3s
      retries: 3

  gateway:
    image: ghcr.io/barbod-biometrics/gateway:latest
    # build: # This is for testing the apis locally and do not have to get the image from the repository (remove the comments if you want to test locally)
    #   context: .
    #   dockerfile: gateway/Dockerfile
    container_name: barbod-gateway
    restart: always
    ports:
      - "8080:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - logs-data:/app/logs
      - ./gateway/internal/infrastructure/jwt:/app/internal/infrastructure/jwt
    depends_on:
      - postgres
      - redis
      - minio
      - jaeger

volumes:
  postgres-data:
  redis-data:
  minio-data:
  logs-data:
    