// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/service"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/usecase"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/communication"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/jwt"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/repository"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/infrastructure/communication/sms"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/infrastructure/database/redis"
	jwt2 "github.com/Barbod-Biometrics/Backend/gateway/internal/infrastructure/jwt"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/infrastructure/repository/postgres"
	"github.com/google/wire"
)

// Injectors from wire.go:

// MAIN INJECTOR
func InitializeApplication() (*Application, error) {
	config := ProvideConfig()
	loggerConfig := ProvideLoggerConfig(config)
	appLogger, err := ProvideAppLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	db := ProvidePostgresDatabase(config)
	redisClient, err := ProvideRedisClient(config)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	cacheRepository := redis.NewCacheRepository(redisClient)
	otpService := service.NewOTPService(cacheRepository, config)
	smsService := ProvideSMSService(config)
	jwtKeyManager := ProvideJWTKeyManager()
	jwtService := service.NewJWTService(config, jwtKeyManager)
	authService := service.NewAuthService(userRepository, otpService, smsService, jwtService)
	userService := service.NewUserService(userRepository)
	generalUserController := ProvideUserController(authService, userService)
	profileRepository := postgres.NewProfileRepository(db)
	minioClient, err := ProvideMinioClient(config)
	if err != nil {
		return nil, err
	}
	profileUsecase := service.NewProfileService(profileRepository, minioClient)
	profileHandler := ProvideProfileHandler(profileUsecase)
	apiKeyRepository := postgres.NewApiKeyRepository(db)
	logger := ProvideGenericLogger(appLogger)
	apiKeyService := service.NewAPIKeyService(apiKeyRepository, logger)
	apiKeyHandler := ProvideAPIKeyController(apiKeyService, logger)
	adminProfileUsecase := service.NewAdminProfileService(profileRepository)
	adminProfileHandler := ProvideAdminProfileHandler(adminProfileUsecase)
	transactionRepository := postgres.NewTransactionRepository(db, logger)
	unitOfWork := postgres.NewGormUnitOfWork(db)
	walletUsecase := service.NewWalletService(profileRepository, transactionRepository, unitOfWork, logger)
	walletHandler := ProvideWalletHandler(walletUsecase, logger)
	transactionService := service.NewTransactionService(transactionRepository, logger)
	transactionHandler := ProvideTransactionHandler(transactionService, logger)
	faceVerificationClient := ProvideFaceVerificationClient(config, logger)
	faceVerificationRepository := postgres.NewFaceVerificationRepository(db)
	faceVerificationService := service.NewFaceVerificationService(faceVerificationClient, logger, faceVerificationRepository)
	faceVerificationHandler := ProvideFaceVerificationHandler(faceVerificationService, logger)
	route := ProvideRouter(generalUserController, profileHandler, apiKeyHandler, adminProfileHandler, walletHandler, transactionHandler, apiKeyService, logger, jwtKeyManager, faceVerificationHandler, config)
	telemetry, err := ProvideTelemetry(config)
	if err != nil {
		return nil, err
	}
	application := NewApplication(config, appLogger, db, redisClient, route, minioClient, telemetry)
	return application, nil
}

// wire.go:

// Config Set
var ConfigSet = wire.NewSet(
	ProvideConfig,
	ProvideLoggerConfig,
)

// Logger Set
var LoggerSet = wire.NewSet(
	ProvideAppLogger,
	ProvideGenericLogger,
)

// Infrastructure Set
var InfrastructureSet = wire.NewSet(
	ProvidePostgresDatabase,
	ProvideRedisClient,
	ProvideMinioClient,
	ProvideTelemetry,
	ProvideJWTKeyManager,
	ProvideSMSService,
	ProvideTranslator,
	ProvideLocalizationTranslator,
	ProvideRecovery,
	ProvideFaceVerificationClient, wire.Bind(new(jwt.KeyManager), new(*jwt2.JWTKeyManager)), wire.Bind(new(communication.SMSService), new(*sms.SMSService)),
)

// Repository Set
var RepositorySet = wire.NewSet(postgres.NewUserRepository, postgres.NewGormUnitOfWork, postgres.NewProfileRepository, wire.Bind(new(repository.ProfileRepository), new(*postgres.ProfileRepository)), postgres.NewTransactionRepository, wire.Bind(new(repository.TransactionRepository), new(*postgres.TransactionRepository)), postgres.NewApiKeyRepository, wire.Bind(new(repository.APIKeyRepository), new(*postgres.ApiKeyRepository)), postgres.NewFaceVerificationRepository, wire.Bind(new(repository.FaceVerificationRepository), new(*postgres.FaceVerificationRepository)), redis.NewCacheRepository, wire.Bind(new(repository.CacheRepository), new(*redis.CacheRepository)))

// Service Set
var ServiceSet = wire.NewSet(service.NewProfileService, service.NewWalletService, service.NewAdminProfileService, service.NewUserService, service.NewJWTService, service.NewOTPService, service.NewAuthService, service.NewAPIKeyService, service.NewTransactionService, service.NewFaceVerificationService, wire.Bind(new(usecase.UserUsecase), new(*service.UserService)), wire.Bind(new(usecase.TokenUsecase), new(*service.JWTService)), wire.Bind(new(usecase.OTPUsecase), new(*service.OTPService)), wire.Bind(new(usecase.AuthUsecase), new(*service.AuthService)), wire.Bind(new(usecase.APIKeyUsecase), new(*service.APIKeyService)), wire.Bind(new(usecase.TransactionUsecase), new(*service.TransactionService)), wire.Bind(new(usecase.FaceVerificationUsecase), new(*service.FaceVerificationService)))

// Controller Set
var ControllerSet = wire.NewSet(
	ProvideUserController,
	ProvideProfileHandler,
	ProvideAPIKeyController,
	ProvideAdminProfileHandler,
	ProvideWalletHandler,
	ProvideTransactionHandler,
	ProvideFaceVerificationHandler,
)

// Router Set
var RouterSet = wire.NewSet(
	ProvideRouter,
)
