// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/admin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminProfileUsecase creates a new instance of MockAdminProfileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminProfileUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminProfileUsecase {
	mock := &MockAdminProfileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminProfileUsecase is an autogenerated mock type for the AdminProfileUsecase type
type MockAdminProfileUsecase struct {
	mock.Mock
}

type MockAdminProfileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminProfileUsecase) EXPECT() *MockAdminProfileUsecase_Expecter {
	return &MockAdminProfileUsecase_Expecter{mock: &_m.Mock}
}

// ApproveProfile provides a mock function for the type MockAdminProfileUsecase
func (_mock *MockAdminProfileUsecase) ApproveProfile(ctx context.Context, profileID uint64, req admin.ApproveProfileRequest) error {
	ret := _mock.Called(ctx, profileID, req)

	if len(ret) == 0 {
		panic("no return value specified for ApproveProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, admin.ApproveProfileRequest) error); ok {
		r0 = returnFunc(ctx, profileID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminProfileUsecase_ApproveProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveProfile'
type MockAdminProfileUsecase_ApproveProfile_Call struct {
	*mock.Call
}

// ApproveProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - req admin.ApproveProfileRequest
func (_e *MockAdminProfileUsecase_Expecter) ApproveProfile(ctx interface{}, profileID interface{}, req interface{}) *MockAdminProfileUsecase_ApproveProfile_Call {
	return &MockAdminProfileUsecase_ApproveProfile_Call{Call: _e.mock.On("ApproveProfile", ctx, profileID, req)}
}

func (_c *MockAdminProfileUsecase_ApproveProfile_Call) Run(run func(ctx context.Context, profileID uint64, req admin.ApproveProfileRequest)) *MockAdminProfileUsecase_ApproveProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 admin.ApproveProfileRequest
		if args[2] != nil {
			arg2 = args[2].(admin.ApproveProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminProfileUsecase_ApproveProfile_Call) Return(err error) *MockAdminProfileUsecase_ApproveProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminProfileUsecase_ApproveProfile_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, req admin.ApproveProfileRequest) error) *MockAdminProfileUsecase_ApproveProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileDetail provides a mock function for the type MockAdminProfileUsecase
func (_mock *MockAdminProfileUsecase) GetProfileDetail(ctx context.Context, profileID uint64) (*admin.ProfileDetailResponse, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileDetail")
	}

	var r0 *admin.ProfileDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*admin.ProfileDetailResponse, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *admin.ProfileDetailResponse); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ProfileDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminProfileUsecase_GetProfileDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileDetail'
type MockAdminProfileUsecase_GetProfileDetail_Call struct {
	*mock.Call
}

// GetProfileDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockAdminProfileUsecase_Expecter) GetProfileDetail(ctx interface{}, profileID interface{}) *MockAdminProfileUsecase_GetProfileDetail_Call {
	return &MockAdminProfileUsecase_GetProfileDetail_Call{Call: _e.mock.On("GetProfileDetail", ctx, profileID)}
}

func (_c *MockAdminProfileUsecase_GetProfileDetail_Call) Run(run func(ctx context.Context, profileID uint64)) *MockAdminProfileUsecase_GetProfileDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminProfileUsecase_GetProfileDetail_Call) Return(profileDetailResponse *admin.ProfileDetailResponse, err error) *MockAdminProfileUsecase_GetProfileDetail_Call {
	_c.Call.Return(profileDetailResponse, err)
	return _c
}

func (_c *MockAdminProfileUsecase_GetProfileDetail_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (*admin.ProfileDetailResponse, error)) *MockAdminProfileUsecase_GetProfileDetail_Call {
	_c.Call.Return(run)
	return _c
}

// ListProfiles provides a mock function for the type MockAdminProfileUsecase
func (_mock *MockAdminProfileUsecase) ListProfiles(ctx context.Context, req admin.ListProfilesRequest) (*admin.PaginatedProfilesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 *admin.PaginatedProfilesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.ListProfilesRequest) (*admin.PaginatedProfilesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.ListProfilesRequest) *admin.PaginatedProfilesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedProfilesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.ListProfilesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminProfileUsecase_ListProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProfiles'
type MockAdminProfileUsecase_ListProfiles_Call struct {
	*mock.Call
}

// ListProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - req admin.ListProfilesRequest
func (_e *MockAdminProfileUsecase_Expecter) ListProfiles(ctx interface{}, req interface{}) *MockAdminProfileUsecase_ListProfiles_Call {
	return &MockAdminProfileUsecase_ListProfiles_Call{Call: _e.mock.On("ListProfiles", ctx, req)}
}

func (_c *MockAdminProfileUsecase_ListProfiles_Call) Run(run func(ctx context.Context, req admin.ListProfilesRequest)) *MockAdminProfileUsecase_ListProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.ListProfilesRequest
		if args[1] != nil {
			arg1 = args[1].(admin.ListProfilesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminProfileUsecase_ListProfiles_Call) Return(paginatedProfilesResponse *admin.PaginatedProfilesResponse, err error) *MockAdminProfileUsecase_ListProfiles_Call {
	_c.Call.Return(paginatedProfilesResponse, err)
	return _c
}

func (_c *MockAdminProfileUsecase_ListProfiles_Call) RunAndReturn(run func(ctx context.Context, req admin.ListProfilesRequest) (*admin.PaginatedProfilesResponse, error)) *MockAdminProfileUsecase_ListProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// RejectProfile provides a mock function for the type MockAdminProfileUsecase
func (_mock *MockAdminProfileUsecase) RejectProfile(ctx context.Context, profileID uint64, req admin.RejectProfileRequest) error {
	ret := _mock.Called(ctx, profileID, req)

	if len(ret) == 0 {
		panic("no return value specified for RejectProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, admin.RejectProfileRequest) error); ok {
		r0 = returnFunc(ctx, profileID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminProfileUsecase_RejectProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectProfile'
type MockAdminProfileUsecase_RejectProfile_Call struct {
	*mock.Call
}

// RejectProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - req admin.RejectProfileRequest
func (_e *MockAdminProfileUsecase_Expecter) RejectProfile(ctx interface{}, profileID interface{}, req interface{}) *MockAdminProfileUsecase_RejectProfile_Call {
	return &MockAdminProfileUsecase_RejectProfile_Call{Call: _e.mock.On("RejectProfile", ctx, profileID, req)}
}

func (_c *MockAdminProfileUsecase_RejectProfile_Call) Run(run func(ctx context.Context, profileID uint64, req admin.RejectProfileRequest)) *MockAdminProfileUsecase_RejectProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 admin.RejectProfileRequest
		if args[2] != nil {
			arg2 = args[2].(admin.RejectProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminProfileUsecase_RejectProfile_Call) Return(err error) *MockAdminProfileUsecase_RejectProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminProfileUsecase_RejectProfile_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, req admin.RejectProfileRequest) error) *MockAdminProfileUsecase_RejectProfile_Call {
	_c.Call.Return(run)
	return _c
}
