// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Create(ctx context.Context, apiKey *entity.APIKey) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.APIKey) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *entity.APIKey
func (_e *MockAPIKeyRepository_Expecter) Create(ctx interface{}, apiKey interface{}) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, apiKey *entity.APIKey)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.APIKey
		if args[1] != nil {
			arg1 = args[1].(*entity.APIKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(err error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, apiKey *entity.APIKey) error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByProfileID provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) GetActiveByProfileID(ctx context.Context, profileID uint64) (*entity.APIKey, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByProfileID")
	}

	var r0 *entity.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.APIKey, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.APIKey); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_GetActiveByProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByProfileID'
type MockAPIKeyRepository_GetActiveByProfileID_Call struct {
	*mock.Call
}

// GetActiveByProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockAPIKeyRepository_Expecter) GetActiveByProfileID(ctx interface{}, profileID interface{}) *MockAPIKeyRepository_GetActiveByProfileID_Call {
	return &MockAPIKeyRepository_GetActiveByProfileID_Call{Call: _e.mock.On("GetActiveByProfileID", ctx, profileID)}
}

func (_c *MockAPIKeyRepository_GetActiveByProfileID_Call) Run(run func(ctx context.Context, profileID uint64)) *MockAPIKeyRepository_GetActiveByProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetActiveByProfileID_Call) Return(aPIKey *entity.APIKey, err error) *MockAPIKeyRepository_GetActiveByProfileID_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_GetActiveByProfileID_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (*entity.APIKey, error)) *MockAPIKeyRepository_GetActiveByProfileID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPrefix provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) GetByPrefix(ctx context.Context, prefix string) (*entity.APIKey, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetByPrefix")
	}

	var r0 *entity.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.APIKey, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.APIKey); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_GetByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPrefix'
type MockAPIKeyRepository_GetByPrefix_Call struct {
	*mock.Call
}

// GetByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockAPIKeyRepository_Expecter) GetByPrefix(ctx interface{}, prefix interface{}) *MockAPIKeyRepository_GetByPrefix_Call {
	return &MockAPIKeyRepository_GetByPrefix_Call{Call: _e.mock.On("GetByPrefix", ctx, prefix)}
}

func (_c *MockAPIKeyRepository_GetByPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockAPIKeyRepository_GetByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByPrefix_Call) Return(aPIKey *entity.APIKey, err error) *MockAPIKeyRepository_GetByPrefix_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_GetByPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) (*entity.APIKey, error)) *MockAPIKeyRepository_GetByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Revoke(ctx context.Context, keyID string) error {
	ret := _mock.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, keyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeyRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockAPIKeyRepository_Expecter) Revoke(ctx interface{}, keyID interface{}) *MockAPIKeyRepository_Revoke_Call {
	return &MockAPIKeyRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, keyID)}
}

func (_c *MockAPIKeyRepository_Revoke_Call) Run(run func(ctx context.Context, keyID string)) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) Return(err error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, keyID string) error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
