// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyUsecase creates a new instance of MockAPIKeyUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyUsecase {
	mock := &MockAPIKeyUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyUsecase is an autogenerated mock type for the APIKeyUsecase type
type MockAPIKeyUsecase struct {
	mock.Mock
}

type MockAPIKeyUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyUsecase) EXPECT() *MockAPIKeyUsecase_Expecter {
	return &MockAPIKeyUsecase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAPIKeyUsecase
func (_mock *MockAPIKeyUsecase) Authenticate(ctx context.Context, rawKey string) (uint64, error) {
	ret := _mock.Called(ctx, rawKey)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return returnFunc(ctx, rawKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = returnFunc(ctx, rawKey)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyUsecase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAPIKeyUsecase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - rawKey string
func (_e *MockAPIKeyUsecase_Expecter) Authenticate(ctx interface{}, rawKey interface{}) *MockAPIKeyUsecase_Authenticate_Call {
	return &MockAPIKeyUsecase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, rawKey)}
}

func (_c *MockAPIKeyUsecase_Authenticate_Call) Run(run func(ctx context.Context, rawKey string)) *MockAPIKeyUsecase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyUsecase_Authenticate_Call) Return(v uint64, err error) *MockAPIKeyUsecase_Authenticate_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAPIKeyUsecase_Authenticate_Call) RunAndReturn(run func(ctx context.Context, rawKey string) (uint64, error)) *MockAPIKeyUsecase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateKey provides a mock function for the type MockAPIKeyUsecase
func (_mock *MockAPIKeyUsecase) GenerateKey(ctx context.Context, profileID uint64) (string, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (string, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyUsecase_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockAPIKeyUsecase_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockAPIKeyUsecase_Expecter) GenerateKey(ctx interface{}, profileID interface{}) *MockAPIKeyUsecase_GenerateKey_Call {
	return &MockAPIKeyUsecase_GenerateKey_Call{Call: _e.mock.On("GenerateKey", ctx, profileID)}
}

func (_c *MockAPIKeyUsecase_GenerateKey_Call) Run(run func(ctx context.Context, profileID uint64)) *MockAPIKeyUsecase_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyUsecase_GenerateKey_Call) Return(s string, err error) *MockAPIKeyUsecase_GenerateKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAPIKeyUsecase_GenerateKey_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (string, error)) *MockAPIKeyUsecase_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateKey provides a mock function for the type MockAPIKeyUsecase
func (_mock *MockAPIKeyUsecase) RegenerateKey(ctx context.Context, profileID uint64) (string, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (string, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyUsecase_RegenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateKey'
type MockAPIKeyUsecase_RegenerateKey_Call struct {
	*mock.Call
}

// RegenerateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockAPIKeyUsecase_Expecter) RegenerateKey(ctx interface{}, profileID interface{}) *MockAPIKeyUsecase_RegenerateKey_Call {
	return &MockAPIKeyUsecase_RegenerateKey_Call{Call: _e.mock.On("RegenerateKey", ctx, profileID)}
}

func (_c *MockAPIKeyUsecase_RegenerateKey_Call) Run(run func(ctx context.Context, profileID uint64)) *MockAPIKeyUsecase_RegenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyUsecase_RegenerateKey_Call) Return(s string, err error) *MockAPIKeyUsecase_RegenerateKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAPIKeyUsecase_RegenerateKey_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (string, error)) *MockAPIKeyUsecase_RegenerateKey_Call {
	_c.Call.Return(run)
	return _c
}
