// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppLogger creates a new instance of MockAppLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppLogger {
	mock := &MockAppLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppLogger is an autogenerated mock type for the AppLogger type
type MockAppLogger struct {
	mock.Mock
}

type MockAppLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppLogger) EXPECT() *MockAppLogger_Expecter {
	return &MockAppLogger_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Close() {
	_mock.Called()
	return
}

// MockAppLogger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAppLogger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAppLogger_Expecter) Close() *MockAppLogger_Close_Call {
	return &MockAppLogger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAppLogger_Close_Call) Run(run func()) *MockAppLogger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppLogger_Close_Call) Return() *MockAppLogger_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Close_Call) RunAndReturn(run func()) *MockAppLogger_Close_Call {
	_c.Run(run)
	return _c
}

// Debug provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Debug(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockAppLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockAppLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockAppLogger_Expecter) Debug(msg interface{}, fields ...interface{}) *MockAppLogger_Debug_Call {
	return &MockAppLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockAppLogger_Debug_Call) Run(run func(msg string, fields ...logger.Field)) *MockAppLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppLogger_Debug_Call) Return() *MockAppLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Debug_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockAppLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Error(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockAppLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockAppLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockAppLogger_Expecter) Error(msg interface{}, fields ...interface{}) *MockAppLogger_Error_Call {
	return &MockAppLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockAppLogger_Error_Call) Run(run func(msg string, fields ...logger.Field)) *MockAppLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppLogger_Error_Call) Return() *MockAppLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Error_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockAppLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Fatal(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockAppLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockAppLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockAppLogger_Expecter) Fatal(msg interface{}, fields ...interface{}) *MockAppLogger_Fatal_Call {
	return &MockAppLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockAppLogger_Fatal_Call) Run(run func(msg string, fields ...logger.Field)) *MockAppLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppLogger_Fatal_Call) Return() *MockAppLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Fatal_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockAppLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Info(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockAppLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockAppLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockAppLogger_Expecter) Info(msg interface{}, fields ...interface{}) *MockAppLogger_Info_Call {
	return &MockAppLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockAppLogger_Info_Call) Run(run func(msg string, fields ...logger.Field)) *MockAppLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppLogger_Info_Call) Return() *MockAppLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Info_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockAppLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) Warn(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockAppLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockAppLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockAppLogger_Expecter) Warn(msg interface{}, fields ...interface{}) *MockAppLogger_Warn_Call {
	return &MockAppLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockAppLogger_Warn_Call) Run(run func(msg string, fields ...logger.Field)) *MockAppLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppLogger_Warn_Call) Return() *MockAppLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAppLogger_Warn_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockAppLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WithFields provides a mock function for the type MockAppLogger
func (_mock *MockAppLogger) WithFields(fields map[string]interface{}) logger.Logger {
	ret := _mock.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for WithFields")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) logger.Logger); ok {
		r0 = returnFunc(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockAppLogger_WithFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithFields'
type MockAppLogger_WithFields_Call struct {
	*mock.Call
}

// WithFields is a helper method to define mock.On call
//   - fields map[string]interface{}
func (_e *MockAppLogger_Expecter) WithFields(fields interface{}) *MockAppLogger_WithFields_Call {
	return &MockAppLogger_WithFields_Call{Call: _e.mock.On("WithFields", fields)}
}

func (_c *MockAppLogger_WithFields_Call) Run(run func(fields map[string]interface{})) *MockAppLogger_WithFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppLogger_WithFields_Call) Return(logger1 logger.Logger) *MockAppLogger_WithFields_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockAppLogger_WithFields_Call) RunAndReturn(run func(fields map[string]interface{}) logger.Logger) *MockAppLogger_WithFields_Call {
	_c.Call.Return(run)
	return _c
}
