// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// RequestOTP provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) RequestOTP(ctx context.Context, req auth.RequestOTPRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RequestOTPRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_RequestOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestOTP'
type MockAuthUsecase_RequestOTP_Call struct {
	*mock.Call
}

// RequestOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.RequestOTPRequest
func (_e *MockAuthUsecase_Expecter) RequestOTP(ctx interface{}, req interface{}) *MockAuthUsecase_RequestOTP_Call {
	return &MockAuthUsecase_RequestOTP_Call{Call: _e.mock.On("RequestOTP", ctx, req)}
}

func (_c *MockAuthUsecase_RequestOTP_Call) Run(run func(ctx context.Context, req auth.RequestOTPRequest)) *MockAuthUsecase_RequestOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RequestOTPRequest
		if args[1] != nil {
			arg1 = args[1].(auth.RequestOTPRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_RequestOTP_Call) Return(err error) *MockAuthUsecase_RequestOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_RequestOTP_Call) RunAndReturn(run func(ctx context.Context, req auth.RequestOTPRequest) error) *MockAuthUsecase_RequestOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) VerifyOTP(ctx context.Context, req auth.VerifyOTPRequest) (*auth.UserInfoResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *auth.UserInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.VerifyOTPRequest) (*auth.UserInfoResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.VerifyOTPRequest) *auth.UserInfoResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.VerifyOTPRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockAuthUsecase_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.VerifyOTPRequest
func (_e *MockAuthUsecase_Expecter) VerifyOTP(ctx interface{}, req interface{}) *MockAuthUsecase_VerifyOTP_Call {
	return &MockAuthUsecase_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, req)}
}

func (_c *MockAuthUsecase_VerifyOTP_Call) Run(run func(ctx context.Context, req auth.VerifyOTPRequest)) *MockAuthUsecase_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.VerifyOTPRequest
		if args[1] != nil {
			arg1 = args[1].(auth.VerifyOTPRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_VerifyOTP_Call) Return(userInfoResponse *auth.UserInfoResponse, err error) *MockAuthUsecase_VerifyOTP_Call {
	_c.Call.Return(userInfoResponse, err)
	return _c
}

func (_c *MockAuthUsecase_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, req auth.VerifyOTPRequest) (*auth.UserInfoResponse, error)) *MockAuthUsecase_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
