// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Delete(ctx context.Context, key ...string) error {
	var tmpRet mock.Arguments
	if len(key) > 0 {
		tmpRet = _mock.Called(ctx, key)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, key...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key ...string
func (_e *MockCacheRepository_Expecter) Delete(ctx interface{}, key ...interface{}) *MockCacheRepository_Delete_Call {
	return &MockCacheRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, key...)...)}
}

func (_c *MockCacheRepository_Delete_Call) Run(run func(ctx context.Context, key ...string)) *MockCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Delete_Call) Return(err error) *MockCacheRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key ...string) error) *MockCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCacheRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) Exists(ctx interface{}, key interface{}) *MockCacheRepository_Exists_Call {
	return &MockCacheRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockCacheRepository_Exists_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Exists_Call) Return(b bool, err error) *MockCacheRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCacheRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockCacheRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Expire provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Expire(ctx context.Context, key string, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type MockCacheRepository_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiration time.Duration
func (_e *MockCacheRepository_Expecter) Expire(ctx interface{}, key interface{}, expiration interface{}) *MockCacheRepository_Expire_Call {
	return &MockCacheRepository_Expire_Call{Call: _e.mock.On("Expire", ctx, key, expiration)}
}

func (_c *MockCacheRepository_Expire_Call) Run(run func(ctx context.Context, key string, expiration time.Duration)) *MockCacheRepository_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Expire_Call) Return(err error) *MockCacheRepository_Expire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Expire_Call) RunAndReturn(run func(ctx context.Context, key string, expiration time.Duration) error) *MockCacheRepository_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) Get(ctx interface{}, key interface{}) *MockCacheRepository_Get_Call {
	return &MockCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheRepository_Get_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Get_Call) Return(s string, err error) *MockCacheRepository_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCacheRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetTTL provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) GetTTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTTL")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_GetTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTTL'
type MockCacheRepository_GetTTL_Call struct {
	*mock.Call
}

// GetTTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) GetTTL(ctx interface{}, key interface{}) *MockCacheRepository_GetTTL_Call {
	return &MockCacheRepository_GetTTL_Call{Call: _e.mock.On("GetTTL", ctx, key)}
}

func (_c *MockCacheRepository_GetTTL_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_GetTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_GetTTL_Call) Return(duration time.Duration, err error) *MockCacheRepository_GetTTL_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *MockCacheRepository_GetTTL_Call) RunAndReturn(run func(ctx context.Context, key string) (time.Duration, error)) *MockCacheRepository_GetTTL_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Increment(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockCacheRepository_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) Increment(ctx interface{}, key interface{}) *MockCacheRepository_Increment_Call {
	return &MockCacheRepository_Increment_Call{Call: _e.mock.On("Increment", ctx, key)}
}

func (_c *MockCacheRepository_Increment_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Increment_Call) Return(n int64, err error) *MockCacheRepository_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCacheRepository_Increment_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *MockCacheRepository_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *MockCacheRepository_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockCacheRepository_Set_Call {
	return &MockCacheRepository_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockCacheRepository_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *MockCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Set_Call) Return(err error) *MockCacheRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, expiration time.Duration) error) *MockCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
