// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockEmailService
func (_mock *MockEmailService) Send(ctx context.Context, to string, subject string, body string) error {
	ret := _mock.Called(ctx, to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
func (_e *MockEmailService_Expecter) Send(ctx interface{}, to interface{}, subject interface{}, body interface{}) *MockEmailService_Send_Call {
	return &MockEmailService_Send_Call{Call: _e.mock.On("Send", ctx, to, subject, body)}
}

func (_c *MockEmailService_Send_Call) Run(run func(ctx context.Context, to string, subject string, body string)) *MockEmailService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_Send_Call) Return(err error) *MockEmailService_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_Send_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, body string) error) *MockEmailService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendWithTemplate provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendWithTemplate(ctx context.Context, to string, subject string, templateName string, data map[string]interface{}) error {
	ret := _mock.Called(ctx, to, subject, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for SendWithTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, to, subject, templateName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendWithTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWithTemplate'
type MockEmailService_SendWithTemplate_Call struct {
	*mock.Call
}

// SendWithTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - templateName string
//   - data map[string]interface{}
func (_e *MockEmailService_Expecter) SendWithTemplate(ctx interface{}, to interface{}, subject interface{}, templateName interface{}, data interface{}) *MockEmailService_SendWithTemplate_Call {
	return &MockEmailService_SendWithTemplate_Call{Call: _e.mock.On("SendWithTemplate", ctx, to, subject, templateName, data)}
}

func (_c *MockEmailService_SendWithTemplate_Call) Run(run func(ctx context.Context, to string, subject string, templateName string, data map[string]interface{})) *MockEmailService_SendWithTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockEmailService_SendWithTemplate_Call) Return(err error) *MockEmailService_SendWithTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendWithTemplate_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, templateName string, data map[string]interface{}) error) *MockEmailService_SendWithTemplate_Call {
	_c.Call.Return(run)
	return _c
}
