// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFaceVerificationRepository creates a new instance of MockFaceVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFaceVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFaceVerificationRepository {
	mock := &MockFaceVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFaceVerificationRepository is an autogenerated mock type for the FaceVerificationRepository type
type MockFaceVerificationRepository struct {
	mock.Mock
}

type MockFaceVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFaceVerificationRepository) EXPECT() *MockFaceVerificationRepository_Expecter {
	return &MockFaceVerificationRepository_Expecter{mock: &_m.Mock}
}

// GetResultsByProfileID provides a mock function for the type MockFaceVerificationRepository
func (_mock *MockFaceVerificationRepository) GetResultsByProfileID(ctx context.Context, profileID uint64) ([]*entity.FaceVerificationRecord, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetResultsByProfileID")
	}

	var r0 []*entity.FaceVerificationRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*entity.FaceVerificationRecord, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*entity.FaceVerificationRecord); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.FaceVerificationRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFaceVerificationRepository_GetResultsByProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResultsByProfileID'
type MockFaceVerificationRepository_GetResultsByProfileID_Call struct {
	*mock.Call
}

// GetResultsByProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockFaceVerificationRepository_Expecter) GetResultsByProfileID(ctx interface{}, profileID interface{}) *MockFaceVerificationRepository_GetResultsByProfileID_Call {
	return &MockFaceVerificationRepository_GetResultsByProfileID_Call{Call: _e.mock.On("GetResultsByProfileID", ctx, profileID)}
}

func (_c *MockFaceVerificationRepository_GetResultsByProfileID_Call) Run(run func(ctx context.Context, profileID uint64)) *MockFaceVerificationRepository_GetResultsByProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFaceVerificationRepository_GetResultsByProfileID_Call) Return(faceVerificationRecords []*entity.FaceVerificationRecord, err error) *MockFaceVerificationRepository_GetResultsByProfileID_Call {
	_c.Call.Return(faceVerificationRecords, err)
	return _c
}

func (_c *MockFaceVerificationRepository_GetResultsByProfileID_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) ([]*entity.FaceVerificationRecord, error)) *MockFaceVerificationRepository_GetResultsByProfileID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResult provides a mock function for the type MockFaceVerificationRepository
func (_mock *MockFaceVerificationRepository) SaveResult(ctx context.Context, profileID uint64, result *entity.FaceVerificationRecord) error {
	ret := _mock.Called(ctx, profileID, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *entity.FaceVerificationRecord) error); ok {
		r0 = returnFunc(ctx, profileID, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFaceVerificationRepository_SaveResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResult'
type MockFaceVerificationRepository_SaveResult_Call struct {
	*mock.Call
}

// SaveResult is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - result *entity.FaceVerificationRecord
func (_e *MockFaceVerificationRepository_Expecter) SaveResult(ctx interface{}, profileID interface{}, result interface{}) *MockFaceVerificationRepository_SaveResult_Call {
	return &MockFaceVerificationRepository_SaveResult_Call{Call: _e.mock.On("SaveResult", ctx, profileID, result)}
}

func (_c *MockFaceVerificationRepository_SaveResult_Call) Run(run func(ctx context.Context, profileID uint64, result *entity.FaceVerificationRecord)) *MockFaceVerificationRepository_SaveResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *entity.FaceVerificationRecord
		if args[2] != nil {
			arg2 = args[2].(*entity.FaceVerificationRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFaceVerificationRepository_SaveResult_Call) Return(err error) *MockFaceVerificationRepository_SaveResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFaceVerificationRepository_SaveResult_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, result *entity.FaceVerificationRecord) error) *MockFaceVerificationRepository_SaveResult_Call {
	_c.Call.Return(run)
	return _c
}
