// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/face_verification"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFaceVerificationUsecase creates a new instance of MockFaceVerificationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFaceVerificationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFaceVerificationUsecase {
	mock := &MockFaceVerificationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFaceVerificationUsecase is an autogenerated mock type for the FaceVerificationUsecase type
type MockFaceVerificationUsecase struct {
	mock.Mock
}

type MockFaceVerificationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFaceVerificationUsecase) EXPECT() *MockFaceVerificationUsecase_Expecter {
	return &MockFaceVerificationUsecase_Expecter{mock: &_m.Mock}
}

// CropImage provides a mock function for the type MockFaceVerificationUsecase
func (_mock *MockFaceVerificationUsecase) CropImage(ctx context.Context, profileID uint64, image []byte) (*face_verification.CropImageResponse, error) {
	ret := _mock.Called(ctx, profileID, image)

	if len(ret) == 0 {
		panic("no return value specified for CropImage")
	}

	var r0 *face_verification.CropImageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte) (*face_verification.CropImageResponse, error)); ok {
		return returnFunc(ctx, profileID, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte) *face_verification.CropImageResponse); ok {
		r0 = returnFunc(ctx, profileID, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*face_verification.CropImageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, []byte) error); ok {
		r1 = returnFunc(ctx, profileID, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFaceVerificationUsecase_CropImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CropImage'
type MockFaceVerificationUsecase_CropImage_Call struct {
	*mock.Call
}

// CropImage is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - image []byte
func (_e *MockFaceVerificationUsecase_Expecter) CropImage(ctx interface{}, profileID interface{}, image interface{}) *MockFaceVerificationUsecase_CropImage_Call {
	return &MockFaceVerificationUsecase_CropImage_Call{Call: _e.mock.On("CropImage", ctx, profileID, image)}
}

func (_c *MockFaceVerificationUsecase_CropImage_Call) Run(run func(ctx context.Context, profileID uint64, image []byte)) *MockFaceVerificationUsecase_CropImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFaceVerificationUsecase_CropImage_Call) Return(cropImageResponse *face_verification.CropImageResponse, err error) *MockFaceVerificationUsecase_CropImage_Call {
	_c.Call.Return(cropImageResponse, err)
	return _c
}

func (_c *MockFaceVerificationUsecase_CropImage_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, image []byte) (*face_verification.CropImageResponse, error)) *MockFaceVerificationUsecase_CropImage_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockFaceVerificationUsecase
func (_mock *MockFaceVerificationUsecase) HealthCheck(ctx context.Context) (*face_verification.HealthCheckResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 *face_verification.HealthCheckResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*face_verification.HealthCheckResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *face_verification.HealthCheckResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*face_verification.HealthCheckResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFaceVerificationUsecase_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockFaceVerificationUsecase_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFaceVerificationUsecase_Expecter) HealthCheck(ctx interface{}) *MockFaceVerificationUsecase_HealthCheck_Call {
	return &MockFaceVerificationUsecase_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockFaceVerificationUsecase_HealthCheck_Call) Run(run func(ctx context.Context)) *MockFaceVerificationUsecase_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFaceVerificationUsecase_HealthCheck_Call) Return(healthCheckResponseDTO *face_verification.HealthCheckResponseDTO, err error) *MockFaceVerificationUsecase_HealthCheck_Call {
	_c.Call.Return(healthCheckResponseDTO, err)
	return _c
}

func (_c *MockFaceVerificationUsecase_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) (*face_verification.HealthCheckResponseDTO, error)) *MockFaceVerificationUsecase_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyFace provides a mock function for the type MockFaceVerificationUsecase
func (_mock *MockFaceVerificationUsecase) VerifyFace(ctx context.Context, profileID uint64, photo []byte, video []byte) (*face_verification.FaceVerificationResponse, error) {
	ret := _mock.Called(ctx, profileID, photo, video)

	if len(ret) == 0 {
		panic("no return value specified for VerifyFace")
	}

	var r0 *face_verification.FaceVerificationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte, []byte) (*face_verification.FaceVerificationResponse, error)); ok {
		return returnFunc(ctx, profileID, photo, video)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte, []byte) *face_verification.FaceVerificationResponse); ok {
		r0 = returnFunc(ctx, profileID, photo, video)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*face_verification.FaceVerificationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, []byte, []byte) error); ok {
		r1 = returnFunc(ctx, profileID, photo, video)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFaceVerificationUsecase_VerifyFace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyFace'
type MockFaceVerificationUsecase_VerifyFace_Call struct {
	*mock.Call
}

// VerifyFace is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - photo []byte
//   - video []byte
func (_e *MockFaceVerificationUsecase_Expecter) VerifyFace(ctx interface{}, profileID interface{}, photo interface{}, video interface{}) *MockFaceVerificationUsecase_VerifyFace_Call {
	return &MockFaceVerificationUsecase_VerifyFace_Call{Call: _e.mock.On("VerifyFace", ctx, profileID, photo, video)}
}

func (_c *MockFaceVerificationUsecase_VerifyFace_Call) Run(run func(ctx context.Context, profileID uint64, photo []byte, video []byte)) *MockFaceVerificationUsecase_VerifyFace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFaceVerificationUsecase_VerifyFace_Call) Return(faceVerificationResponse *face_verification.FaceVerificationResponse, err error) *MockFaceVerificationUsecase_VerifyFace_Call {
	_c.Call.Return(faceVerificationResponse, err)
	return _c
}

func (_c *MockFaceVerificationUsecase_VerifyFace_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, photo []byte, video []byte) (*face_verification.FaceVerificationResponse, error)) *MockFaceVerificationUsecase_VerifyFace_Call {
	_c.Call.Return(run)
	return _c
}
