// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto/rsa"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyManager creates a new instance of MockKeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyManager {
	mock := &MockKeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

type MockKeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyManager) EXPECT() *MockKeyManager_Expecter {
	return &MockKeyManager_Expecter{mock: &_m.Mock}
}

// GetPrivateKey provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) GetPrivateKey() *rsa.PrivateKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 *rsa.PrivateKey
	if returnFunc, ok := ret.Get(0).(func() *rsa.PrivateKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}
	return r0
}

// MockKeyManager_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type MockKeyManager_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
func (_e *MockKeyManager_Expecter) GetPrivateKey() *MockKeyManager_GetPrivateKey_Call {
	return &MockKeyManager_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey")}
}

func (_c *MockKeyManager_GetPrivateKey_Call) Run(run func()) *MockKeyManager_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyManager_GetPrivateKey_Call) Return(privateKey *rsa.PrivateKey) *MockKeyManager_GetPrivateKey_Call {
	_c.Call.Return(privateKey)
	return _c
}

func (_c *MockKeyManager_GetPrivateKey_Call) RunAndReturn(run func() *rsa.PrivateKey) *MockKeyManager_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKey provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) GetPublicKey() *rsa.PublicKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *rsa.PublicKey
	if returnFunc, ok := ret.Get(0).(func() *rsa.PublicKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}
	return r0
}

// MockKeyManager_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type MockKeyManager_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
func (_e *MockKeyManager_Expecter) GetPublicKey() *MockKeyManager_GetPublicKey_Call {
	return &MockKeyManager_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey")}
}

func (_c *MockKeyManager_GetPublicKey_Call) Run(run func()) *MockKeyManager_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyManager_GetPublicKey_Call) Return(publicKey *rsa.PublicKey) *MockKeyManager_GetPublicKey_Call {
	_c.Call.Return(publicKey)
	return _c
}

func (_c *MockKeyManager_GetPublicKey_Call) RunAndReturn(run func() *rsa.PublicKey) *MockKeyManager_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// LoadKeys provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) LoadKeys(privateKeyPath string, publicKeyPath string) error {
	ret := _mock.Called(privateKeyPath, publicKeyPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(privateKeyPath, publicKeyPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyManager_LoadKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadKeys'
type MockKeyManager_LoadKeys_Call struct {
	*mock.Call
}

// LoadKeys is a helper method to define mock.On call
//   - privateKeyPath string
//   - publicKeyPath string
func (_e *MockKeyManager_Expecter) LoadKeys(privateKeyPath interface{}, publicKeyPath interface{}) *MockKeyManager_LoadKeys_Call {
	return &MockKeyManager_LoadKeys_Call{Call: _e.mock.On("LoadKeys", privateKeyPath, publicKeyPath)}
}

func (_c *MockKeyManager_LoadKeys_Call) Run(run func(privateKeyPath string, publicKeyPath string)) *MockKeyManager_LoadKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_LoadKeys_Call) Return(err error) *MockKeyManager_LoadKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyManager_LoadKeys_Call) RunAndReturn(run func(privateKeyPath string, publicKeyPath string) error) *MockKeyManager_LoadKeys_Call {
	_c.Call.Return(run)
	return _c
}
