// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOCRRepository creates a new instance of MockOCRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOCRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOCRRepository {
	mock := &MockOCRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOCRRepository is an autogenerated mock type for the OCRRepository type
type MockOCRRepository struct {
	mock.Mock
}

type MockOCRRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOCRRepository) EXPECT() *MockOCRRepository_Expecter {
	return &MockOCRRepository_Expecter{mock: &_m.Mock}
}

// GetResultsByProfileID provides a mock function for the type MockOCRRepository
func (_mock *MockOCRRepository) GetResultsByProfileID(ctx context.Context, profileID uint64) ([]*entity.OCRRecord, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetResultsByProfileID")
	}

	var r0 []*entity.OCRRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*entity.OCRRecord, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*entity.OCRRecord); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OCRRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOCRRepository_GetResultsByProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResultsByProfileID'
type MockOCRRepository_GetResultsByProfileID_Call struct {
	*mock.Call
}

// GetResultsByProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockOCRRepository_Expecter) GetResultsByProfileID(ctx interface{}, profileID interface{}) *MockOCRRepository_GetResultsByProfileID_Call {
	return &MockOCRRepository_GetResultsByProfileID_Call{Call: _e.mock.On("GetResultsByProfileID", ctx, profileID)}
}

func (_c *MockOCRRepository_GetResultsByProfileID_Call) Run(run func(ctx context.Context, profileID uint64)) *MockOCRRepository_GetResultsByProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOCRRepository_GetResultsByProfileID_Call) Return(oCRRecords []*entity.OCRRecord, err error) *MockOCRRepository_GetResultsByProfileID_Call {
	_c.Call.Return(oCRRecords, err)
	return _c
}

func (_c *MockOCRRepository_GetResultsByProfileID_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) ([]*entity.OCRRecord, error)) *MockOCRRepository_GetResultsByProfileID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResult provides a mock function for the type MockOCRRepository
func (_mock *MockOCRRepository) SaveResult(ctx context.Context, profileID uint64, result *entity.OCRRecord) error {
	ret := _mock.Called(ctx, profileID, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *entity.OCRRecord) error); ok {
		r0 = returnFunc(ctx, profileID, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOCRRepository_SaveResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResult'
type MockOCRRepository_SaveResult_Call struct {
	*mock.Call
}

// SaveResult is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - result *entity.OCRRecord
func (_e *MockOCRRepository_Expecter) SaveResult(ctx interface{}, profileID interface{}, result interface{}) *MockOCRRepository_SaveResult_Call {
	return &MockOCRRepository_SaveResult_Call{Call: _e.mock.On("SaveResult", ctx, profileID, result)}
}

func (_c *MockOCRRepository_SaveResult_Call) Run(run func(ctx context.Context, profileID uint64, result *entity.OCRRecord)) *MockOCRRepository_SaveResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *entity.OCRRecord
		if args[2] != nil {
			arg2 = args[2].(*entity.OCRRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOCRRepository_SaveResult_Call) Return(err error) *MockOCRRepository_SaveResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOCRRepository_SaveResult_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, result *entity.OCRRecord) error) *MockOCRRepository_SaveResult_Call {
	_c.Call.Return(run)
	return _c
}
