// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/ocr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOCRUsecase creates a new instance of MockOCRUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOCRUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOCRUsecase {
	mock := &MockOCRUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOCRUsecase is an autogenerated mock type for the OCRUsecase type
type MockOCRUsecase struct {
	mock.Mock
}

type MockOCRUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOCRUsecase) EXPECT() *MockOCRUsecase_Expecter {
	return &MockOCRUsecase_Expecter{mock: &_m.Mock}
}

// ExtractText provides a mock function for the type MockOCRUsecase
func (_mock *MockOCRUsecase) ExtractText(ctx context.Context, profileID uint64, image []byte) (*ocr.OCRResponse, error) {
	ret := _mock.Called(ctx, profileID, image)

	if len(ret) == 0 {
		panic("no return value specified for ExtractText")
	}

	var r0 *ocr.OCRResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte) (*ocr.OCRResponse, error)); ok {
		return returnFunc(ctx, profileID, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte) *ocr.OCRResponse); ok {
		r0 = returnFunc(ctx, profileID, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocr.OCRResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, []byte) error); ok {
		r1 = returnFunc(ctx, profileID, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOCRUsecase_ExtractText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractText'
type MockOCRUsecase_ExtractText_Call struct {
	*mock.Call
}

// ExtractText is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - image []byte
func (_e *MockOCRUsecase_Expecter) ExtractText(ctx interface{}, profileID interface{}, image interface{}) *MockOCRUsecase_ExtractText_Call {
	return &MockOCRUsecase_ExtractText_Call{Call: _e.mock.On("ExtractText", ctx, profileID, image)}
}

func (_c *MockOCRUsecase_ExtractText_Call) Run(run func(ctx context.Context, profileID uint64, image []byte)) *MockOCRUsecase_ExtractText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOCRUsecase_ExtractText_Call) Return(oCRResponse *ocr.OCRResponse, err error) *MockOCRUsecase_ExtractText_Call {
	_c.Call.Return(oCRResponse, err)
	return _c
}

func (_c *MockOCRUsecase_ExtractText_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, image []byte) (*ocr.OCRResponse, error)) *MockOCRUsecase_ExtractText_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockOCRUsecase
func (_mock *MockOCRUsecase) HealthCheck(ctx context.Context) (*ocr.HealthCheckResponseDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 *ocr.HealthCheckResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ocr.HealthCheckResponseDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ocr.HealthCheckResponseDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocr.HealthCheckResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOCRUsecase_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockOCRUsecase_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOCRUsecase_Expecter) HealthCheck(ctx interface{}) *MockOCRUsecase_HealthCheck_Call {
	return &MockOCRUsecase_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockOCRUsecase_HealthCheck_Call) Run(run func(ctx context.Context)) *MockOCRUsecase_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOCRUsecase_HealthCheck_Call) Return(healthCheckResponseDTO *ocr.HealthCheckResponseDTO, err error) *MockOCRUsecase_HealthCheck_Call {
	_c.Call.Return(healthCheckResponseDTO, err)
	return _c
}

func (_c *MockOCRUsecase_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) (*ocr.HealthCheckResponseDTO, error)) *MockOCRUsecase_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}
