// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOTPUsecase creates a new instance of MockOTPUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPUsecase {
	mock := &MockOTPUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOTPUsecase is an autogenerated mock type for the OTPUsecase type
type MockOTPUsecase struct {
	mock.Mock
}

type MockOTPUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPUsecase) EXPECT() *MockOTPUsecase_Expecter {
	return &MockOTPUsecase_Expecter{mock: &_m.Mock}
}

// GenerateAndStoreOTP provides a mock function for the type MockOTPUsecase
func (_mock *MockOTPUsecase) GenerateAndStoreOTP(ctx context.Context, phoneNumber string) (string, error) {
	ret := _mock.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAndStoreOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, phoneNumber)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOTPUsecase_GenerateAndStoreOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAndStoreOTP'
type MockOTPUsecase_GenerateAndStoreOTP_Call struct {
	*mock.Call
}

// GenerateAndStoreOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockOTPUsecase_Expecter) GenerateAndStoreOTP(ctx interface{}, phoneNumber interface{}) *MockOTPUsecase_GenerateAndStoreOTP_Call {
	return &MockOTPUsecase_GenerateAndStoreOTP_Call{Call: _e.mock.On("GenerateAndStoreOTP", ctx, phoneNumber)}
}

func (_c *MockOTPUsecase_GenerateAndStoreOTP_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockOTPUsecase_GenerateAndStoreOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOTPUsecase_GenerateAndStoreOTP_Call) Return(plainOTP string, err error) *MockOTPUsecase_GenerateAndStoreOTP_Call {
	_c.Call.Return(plainOTP, err)
	return _c
}

func (_c *MockOTPUsecase_GenerateAndStoreOTP_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string) (string, error)) *MockOTPUsecase_GenerateAndStoreOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockOTPUsecase
func (_mock *MockOTPUsecase) VerifyOTP(ctx context.Context, phoneNumber string, otp string) error {
	ret := _mock.Called(ctx, phoneNumber, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, phoneNumber, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOTPUsecase_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockOTPUsecase_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - otp string
func (_e *MockOTPUsecase_Expecter) VerifyOTP(ctx interface{}, phoneNumber interface{}, otp interface{}) *MockOTPUsecase_VerifyOTP_Call {
	return &MockOTPUsecase_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, phoneNumber, otp)}
}

func (_c *MockOTPUsecase_VerifyOTP_Call) Run(run func(ctx context.Context, phoneNumber string, otp string)) *MockOTPUsecase_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOTPUsecase_VerifyOTP_Call) Return(err error) *MockOTPUsecase_VerifyOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOTPUsecase_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string, otp string) error) *MockOTPUsecase_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
