// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Create(ctx context.Context, profile *entity.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *entity.Profile
func (_e *MockProfileRepository_Expecter) Create(ctx interface{}, profile interface{}) *MockProfileRepository_Create_Call {
	return &MockProfileRepository_Create_Call{Call: _e.mock.On("Create", ctx, profile)}
}

func (_c *MockProfileRepository_Create_Call) Run(run func(ctx context.Context, profile *entity.Profile)) *MockProfileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Profile
		if args[1] != nil {
			arg1 = args[1].(*entity.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Create_Call) Return(err error) *MockProfileRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_Create_Call) RunAndReturn(run func(ctx context.Context, profile *entity.Profile) error) *MockProfileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) GetByID(ctx context.Context, profileID uint64) (*entity.Profile, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Profile, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Profile); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProfileRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockProfileRepository_Expecter) GetByID(ctx interface{}, profileID interface{}) *MockProfileRepository_GetByID_Call {
	return &MockProfileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, profileID)}
}

func (_c *MockProfileRepository_GetByID_Call) Run(run func(ctx context.Context, profileID uint64)) *MockProfileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_GetByID_Call) Return(profile *entity.Profile, err error) *MockProfileRepository_GetByID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (*entity.Profile, error)) *MockProfileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) GetByUserID(ctx context.Context, userID uint64) ([]*entity.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*entity.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*entity.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockProfileRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockProfileRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockProfileRepository_GetByUserID_Call {
	return &MockProfileRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockProfileRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_GetByUserID_Call) Return(profiles []*entity.Profile, err error) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *MockProfileRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]*entity.Profile, error)) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalProfileByUserID provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) GetPersonalProfileByUserID(ctx context.Context, userID uint64) (*entity.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalProfileByUserID")
	}

	var r0 *entity.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_GetPersonalProfileByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalProfileByUserID'
type MockProfileRepository_GetPersonalProfileByUserID_Call struct {
	*mock.Call
}

// GetPersonalProfileByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockProfileRepository_Expecter) GetPersonalProfileByUserID(ctx interface{}, userID interface{}) *MockProfileRepository_GetPersonalProfileByUserID_Call {
	return &MockProfileRepository_GetPersonalProfileByUserID_Call{Call: _e.mock.On("GetPersonalProfileByUserID", ctx, userID)}
}

func (_c *MockProfileRepository_GetPersonalProfileByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *MockProfileRepository_GetPersonalProfileByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_GetPersonalProfileByUserID_Call) Return(profile *entity.Profile, err error) *MockProfileRepository_GetPersonalProfileByUserID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepository_GetPersonalProfileByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*entity.Profile, error)) *MockProfileRepository_GetPersonalProfileByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithFilters provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) ListWithFilters(ctx context.Context, filter repository.ProfileFilter, sort repository.ProfileSort, pagination repository.Pagination) (*repository.PaginatedResult, error) {
	ret := _mock.Called(ctx, filter, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListWithFilters")
	}

	var r0 *repository.PaginatedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileFilter, repository.ProfileSort, repository.Pagination) (*repository.PaginatedResult, error)); ok {
		return returnFunc(ctx, filter, sort, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileFilter, repository.ProfileSort, repository.Pagination) *repository.PaginatedResult); ok {
		r0 = returnFunc(ctx, filter, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.ProfileFilter, repository.ProfileSort, repository.Pagination) error); ok {
		r1 = returnFunc(ctx, filter, sort, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_ListWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithFilters'
type MockProfileRepository_ListWithFilters_Call struct {
	*mock.Call
}

// ListWithFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ProfileFilter
//   - sort repository.ProfileSort
//   - pagination repository.Pagination
func (_e *MockProfileRepository_Expecter) ListWithFilters(ctx interface{}, filter interface{}, sort interface{}, pagination interface{}) *MockProfileRepository_ListWithFilters_Call {
	return &MockProfileRepository_ListWithFilters_Call{Call: _e.mock.On("ListWithFilters", ctx, filter, sort, pagination)}
}

func (_c *MockProfileRepository_ListWithFilters_Call) Run(run func(ctx context.Context, filter repository.ProfileFilter, sort repository.ProfileSort, pagination repository.Pagination)) *MockProfileRepository_ListWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.ProfileFilter
		if args[1] != nil {
			arg1 = args[1].(repository.ProfileFilter)
		}
		var arg2 repository.ProfileSort
		if args[2] != nil {
			arg2 = args[2].(repository.ProfileSort)
		}
		var arg3 repository.Pagination
		if args[3] != nil {
			arg3 = args[3].(repository.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileRepository_ListWithFilters_Call) Return(paginatedResult *repository.PaginatedResult, err error) *MockProfileRepository_ListWithFilters_Call {
	_c.Call.Return(paginatedResult, err)
	return _c
}

func (_c *MockProfileRepository_ListWithFilters_Call) RunAndReturn(run func(ctx context.Context, filter repository.ProfileFilter, sort repository.ProfileSort, pagination repository.Pagination) (*repository.PaginatedResult, error)) *MockProfileRepository_ListWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Update(ctx context.Context, profile *entity.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *entity.Profile
func (_e *MockProfileRepository_Expecter) Update(ctx interface{}, profile interface{}) *MockProfileRepository_Update_Call {
	return &MockProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, profile)}
}

func (_c *MockProfileRepository_Update_Call) Run(run func(ctx context.Context, profile *entity.Profile)) *MockProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Profile
		if args[1] != nil {
			arg1 = args[1].(*entity.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Update_Call) Return(err error) *MockProfileRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, profile *entity.Profile) error) *MockProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
