// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileUsecase creates a new instance of MockProfileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileUsecase {
	mock := &MockProfileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileUsecase is an autogenerated mock type for the ProfileUsecase type
type MockProfileUsecase struct {
	mock.Mock
}

type MockProfileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileUsecase) EXPECT() *MockProfileUsecase_Expecter {
	return &MockProfileUsecase_Expecter{mock: &_m.Mock}
}

// CreateDraft provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) CreateDraft(ctx context.Context, userID uint64, req profile.CreateProfileRequest) (*profile.ProfileResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraft")
	}

	var r0 *profile.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, profile.CreateProfileRequest) (*profile.ProfileResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, profile.CreateProfileRequest) *profile.ProfileResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, profile.CreateProfileRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_CreateDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraft'
type MockProfileUsecase_CreateDraft_Call struct {
	*mock.Call
}

// CreateDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - req profile.CreateProfileRequest
func (_e *MockProfileUsecase_Expecter) CreateDraft(ctx interface{}, userID interface{}, req interface{}) *MockProfileUsecase_CreateDraft_Call {
	return &MockProfileUsecase_CreateDraft_Call{Call: _e.mock.On("CreateDraft", ctx, userID, req)}
}

func (_c *MockProfileUsecase_CreateDraft_Call) Run(run func(ctx context.Context, userID uint64, req profile.CreateProfileRequest)) *MockProfileUsecase_CreateDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 profile.CreateProfileRequest
		if args[2] != nil {
			arg2 = args[2].(profile.CreateProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_CreateDraft_Call) Return(profileResponse *profile.ProfileResponse, err error) *MockProfileUsecase_CreateDraft_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileUsecase_CreateDraft_Call) RunAndReturn(run func(ctx context.Context, userID uint64, req profile.CreateProfileRequest) (*profile.ProfileResponse, error)) *MockProfileUsecase_CreateDraft_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) GetByID(ctx context.Context, userID uint64, profileID uint64) (*profile.ProfileResponse, error) {
	ret := _mock.Called(ctx, userID, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *profile.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*profile.ProfileResponse, error)); ok {
		return returnFunc(ctx, userID, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *profile.ProfileResponse); ok {
		r0 = returnFunc(ctx, userID, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProfileUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
func (_e *MockProfileUsecase_Expecter) GetByID(ctx interface{}, userID interface{}, profileID interface{}) *MockProfileUsecase_GetByID_Call {
	return &MockProfileUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, profileID)}
}

func (_c *MockProfileUsecase_GetByID_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64)) *MockProfileUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_GetByID_Call) Return(profileResponse *profile.ProfileResponse, err error) *MockProfileUsecase_GetByID_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileUsecase_GetByID_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64) (*profile.ProfileResponse, error)) *MockProfileUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadUrl provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) GetUploadUrl(ctx context.Context, userID uint64, req profile.GetUploadUrlRequest) (*profile.UploadUrlResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadUrl")
	}

	var r0 *profile.UploadUrlResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, profile.GetUploadUrlRequest) (*profile.UploadUrlResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, profile.GetUploadUrlRequest) *profile.UploadUrlResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.UploadUrlResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, profile.GetUploadUrlRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_GetUploadUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadUrl'
type MockProfileUsecase_GetUploadUrl_Call struct {
	*mock.Call
}

// GetUploadUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - req profile.GetUploadUrlRequest
func (_e *MockProfileUsecase_Expecter) GetUploadUrl(ctx interface{}, userID interface{}, req interface{}) *MockProfileUsecase_GetUploadUrl_Call {
	return &MockProfileUsecase_GetUploadUrl_Call{Call: _e.mock.On("GetUploadUrl", ctx, userID, req)}
}

func (_c *MockProfileUsecase_GetUploadUrl_Call) Run(run func(ctx context.Context, userID uint64, req profile.GetUploadUrlRequest)) *MockProfileUsecase_GetUploadUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 profile.GetUploadUrlRequest
		if args[2] != nil {
			arg2 = args[2].(profile.GetUploadUrlRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_GetUploadUrl_Call) Return(uploadUrlResponse *profile.UploadUrlResponse, err error) *MockProfileUsecase_GetUploadUrl_Call {
	_c.Call.Return(uploadUrlResponse, err)
	return _c
}

func (_c *MockProfileUsecase_GetUploadUrl_Call) RunAndReturn(run func(ctx context.Context, userID uint64, req profile.GetUploadUrlRequest) (*profile.UploadUrlResponse, error)) *MockProfileUsecase_GetUploadUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfiles provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) GetUserProfiles(ctx context.Context, userID uint64) ([]*profile.ProfileResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfiles")
	}

	var r0 []*profile.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*profile.ProfileResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*profile.ProfileResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*profile.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_GetUserProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfiles'
type MockProfileUsecase_GetUserProfiles_Call struct {
	*mock.Call
}

// GetUserProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockProfileUsecase_Expecter) GetUserProfiles(ctx interface{}, userID interface{}) *MockProfileUsecase_GetUserProfiles_Call {
	return &MockProfileUsecase_GetUserProfiles_Call{Call: _e.mock.On("GetUserProfiles", ctx, userID)}
}

func (_c *MockProfileUsecase_GetUserProfiles_Call) Run(run func(ctx context.Context, userID uint64)) *MockProfileUsecase_GetUserProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_GetUserProfiles_Call) Return(profileResponses []*profile.ProfileResponse, err error) *MockProfileUsecase_GetUserProfiles_Call {
	_c.Call.Return(profileResponses, err)
	return _c
}

func (_c *MockProfileUsecase_GetUserProfiles_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]*profile.ProfileResponse, error)) *MockProfileUsecase_GetUserProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDocument provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) SaveDocument(ctx context.Context, userID uint64, profileID uint64, req profile.SaveDocumentRequest) error {
	ret := _mock.Called(ctx, userID, profileID, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, profile.SaveDocumentRequest) error); ok {
		r0 = returnFunc(ctx, userID, profileID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileUsecase_SaveDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDocument'
type MockProfileUsecase_SaveDocument_Call struct {
	*mock.Call
}

// SaveDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
//   - req profile.SaveDocumentRequest
func (_e *MockProfileUsecase_Expecter) SaveDocument(ctx interface{}, userID interface{}, profileID interface{}, req interface{}) *MockProfileUsecase_SaveDocument_Call {
	return &MockProfileUsecase_SaveDocument_Call{Call: _e.mock.On("SaveDocument", ctx, userID, profileID, req)}
}

func (_c *MockProfileUsecase_SaveDocument_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64, req profile.SaveDocumentRequest)) *MockProfileUsecase_SaveDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 profile.SaveDocumentRequest
		if args[3] != nil {
			arg3 = args[3].(profile.SaveDocumentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_SaveDocument_Call) Return(err error) *MockProfileUsecase_SaveDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileUsecase_SaveDocument_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64, req profile.SaveDocumentRequest) error) *MockProfileUsecase_SaveDocument_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitProfile provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) SubmitProfile(ctx context.Context, userID uint64, profileID uint64) (*profile.ProfileResponse, error) {
	ret := _mock.Called(ctx, userID, profileID)

	if len(ret) == 0 {
		panic("no return value specified for SubmitProfile")
	}

	var r0 *profile.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*profile.ProfileResponse, error)); ok {
		return returnFunc(ctx, userID, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *profile.ProfileResponse); ok {
		r0 = returnFunc(ctx, userID, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_SubmitProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitProfile'
type MockProfileUsecase_SubmitProfile_Call struct {
	*mock.Call
}

// SubmitProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
func (_e *MockProfileUsecase_Expecter) SubmitProfile(ctx interface{}, userID interface{}, profileID interface{}) *MockProfileUsecase_SubmitProfile_Call {
	return &MockProfileUsecase_SubmitProfile_Call{Call: _e.mock.On("SubmitProfile", ctx, userID, profileID)}
}

func (_c *MockProfileUsecase_SubmitProfile_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64)) *MockProfileUsecase_SubmitProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_SubmitProfile_Call) Return(profileResponse *profile.ProfileResponse, err error) *MockProfileUsecase_SubmitProfile_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileUsecase_SubmitProfile_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64) (*profile.ProfileResponse, error)) *MockProfileUsecase_SubmitProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDraft provides a mock function for the type MockProfileUsecase
func (_mock *MockProfileUsecase) UpdateDraft(ctx context.Context, userID uint64, profileID uint64, req profile.UpdateProfileRequest) (*profile.ProfileResponse, error) {
	ret := _mock.Called(ctx, userID, profileID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraft")
	}

	var r0 *profile.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, profile.UpdateProfileRequest) (*profile.ProfileResponse, error)); ok {
		return returnFunc(ctx, userID, profileID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, profile.UpdateProfileRequest) *profile.ProfileResponse); ok {
		r0 = returnFunc(ctx, userID, profileID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, profile.UpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, userID, profileID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecase_UpdateDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDraft'
type MockProfileUsecase_UpdateDraft_Call struct {
	*mock.Call
}

// UpdateDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
//   - req profile.UpdateProfileRequest
func (_e *MockProfileUsecase_Expecter) UpdateDraft(ctx interface{}, userID interface{}, profileID interface{}, req interface{}) *MockProfileUsecase_UpdateDraft_Call {
	return &MockProfileUsecase_UpdateDraft_Call{Call: _e.mock.On("UpdateDraft", ctx, userID, profileID, req)}
}

func (_c *MockProfileUsecase_UpdateDraft_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64, req profile.UpdateProfileRequest)) *MockProfileUsecase_UpdateDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 profile.UpdateProfileRequest
		if args[3] != nil {
			arg3 = args[3].(profile.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileUsecase_UpdateDraft_Call) Return(profileResponse *profile.ProfileResponse, err error) *MockProfileUsecase_UpdateDraft_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileUsecase_UpdateDraft_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64, req profile.UpdateProfileRequest) (*profile.ProfileResponse, error)) *MockProfileUsecase_UpdateDraft_Call {
	_c.Call.Return(run)
	return _c
}
