// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceRepository creates a new instance of MockServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceRepository {
	mock := &MockServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceRepository is an autogenerated mock type for the ServiceRepository type
type MockServiceRepository struct {
	mock.Mock
}

type MockServiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceRepository) EXPECT() *MockServiceRepository_Expecter {
	return &MockServiceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) Create(ctx context.Context, service *entity.Service) error {
	ret := _mock.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Service) error); ok {
		r0 = returnFunc(ctx, service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - service *entity.Service
func (_e *MockServiceRepository_Expecter) Create(ctx interface{}, service interface{}) *MockServiceRepository_Create_Call {
	return &MockServiceRepository_Create_Call{Call: _e.mock.On("Create", ctx, service)}
}

func (_c *MockServiceRepository_Create_Call) Run(run func(ctx context.Context, service *entity.Service)) *MockServiceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Service
		if args[1] != nil {
			arg1 = args[1].(*entity.Service)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceRepository_Create_Call) Return(err error) *MockServiceRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRepository_Create_Call) RunAndReturn(run func(ctx context.Context, service *entity.Service) error) *MockServiceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) GetByID(ctx context.Context, serviceID uint64) (*entity.Service, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Service, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Service); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockServiceRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID uint64
func (_e *MockServiceRepository_Expecter) GetByID(ctx interface{}, serviceID interface{}) *MockServiceRepository_GetByID_Call {
	return &MockServiceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, serviceID)}
}

func (_c *MockServiceRepository_GetByID_Call) Run(run func(ctx context.Context, serviceID uint64)) *MockServiceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceRepository_GetByID_Call) Return(service *entity.Service, err error) *MockServiceRepository_GetByID_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockServiceRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, serviceID uint64) (*entity.Service, error)) *MockServiceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) GetByName(ctx context.Context, serviceName string) (*entity.Service, error) {
	ret := _mock.Called(ctx, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Service, error)); ok {
		return returnFunc(ctx, serviceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Service); ok {
		r0 = returnFunc(ctx, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serviceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockServiceRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceName string
func (_e *MockServiceRepository_Expecter) GetByName(ctx interface{}, serviceName interface{}) *MockServiceRepository_GetByName_Call {
	return &MockServiceRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, serviceName)}
}

func (_c *MockServiceRepository_GetByName_Call) Run(run func(ctx context.Context, serviceName string)) *MockServiceRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceRepository_GetByName_Call) Return(service *entity.Service, err error) *MockServiceRepository_GetByName_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockServiceRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, serviceName string) (*entity.Service, error)) *MockServiceRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) List(ctx context.Context) ([]*entity.Service, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Service, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Service); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceRepository_Expecter) List(ctx interface{}) *MockServiceRepository_List_Call {
	return &MockServiceRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockServiceRepository_List_Call) Run(run func(ctx context.Context)) *MockServiceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRepository_List_Call) Return(services []*entity.Service, err error) *MockServiceRepository_List_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockServiceRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Service, error)) *MockServiceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) Update(ctx context.Context, service *entity.Service) error {
	ret := _mock.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Service) error); ok {
		r0 = returnFunc(ctx, service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - service *entity.Service
func (_e *MockServiceRepository_Expecter) Update(ctx interface{}, service interface{}) *MockServiceRepository_Update_Call {
	return &MockServiceRepository_Update_Call{Call: _e.mock.On("Update", ctx, service)}
}

func (_c *MockServiceRepository_Update_Call) Run(run func(ctx context.Context, service *entity.Service)) *MockServiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Service
		if args[1] != nil {
			arg1 = args[1].(*entity.Service)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceRepository_Update_Call) Return(err error) *MockServiceRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRepository_Update_Call) RunAndReturn(run func(ctx context.Context, service *entity.Service) error) *MockServiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
