// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSMSService creates a new instance of MockSMSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMSService {
	mock := &MockSMSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSMSService is an autogenerated mock type for the SMSService type
type MockSMSService struct {
	mock.Mock
}

type MockSMSService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMSService) EXPECT() *MockSMSService_Expecter {
	return &MockSMSService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockSMSService
func (_mock *MockSMSService) Send(ctx context.Context, phoneNumber string, message string) error {
	ret := _mock.Called(ctx, phoneNumber, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, phoneNumber, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSMSService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSMSService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - message string
func (_e *MockSMSService_Expecter) Send(ctx interface{}, phoneNumber interface{}, message interface{}) *MockSMSService_Send_Call {
	return &MockSMSService_Send_Call{Call: _e.mock.On("Send", ctx, phoneNumber, message)}
}

func (_c *MockSMSService_Send_Call) Run(run func(ctx context.Context, phoneNumber string, message string)) *MockSMSService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSMSService_Send_Call) Return(err error) *MockSMSService_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSMSService_Send_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string, message string) error) *MockSMSService_Send_Call {
	_c.Call.Return(run)
	return _c
}
