// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/ticket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketUsecase creates a new instance of MockTicketUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketUsecase {
	mock := &MockTicketUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketUsecase is an autogenerated mock type for the TicketUsecase type
type MockTicketUsecase struct {
	mock.Mock
}

type MockTicketUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketUsecase) EXPECT() *MockTicketUsecase_Expecter {
	return &MockTicketUsecase_Expecter{mock: &_m.Mock}
}

// CloseTicket provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) CloseTicket(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool) (*ticket.CloseTicketResponse, error) {
	ret := _mock.Called(ctx, ticketID, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for CloseTicket")
	}

	var r0 *ticket.CloseTicketResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) (*ticket.CloseTicketResponse, error)); ok {
		return returnFunc(ctx, ticketID, userID, isAdmin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) *ticket.CloseTicketResponse); ok {
		r0 = returnFunc(ctx, ticketID, userID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.CloseTicketResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, bool) error); ok {
		r1 = returnFunc(ctx, ticketID, userID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_CloseTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseTicket'
type MockTicketUsecase_CloseTicket_Call struct {
	*mock.Call
}

// CloseTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
//   - userID uint64
//   - isAdmin bool
func (_e *MockTicketUsecase_Expecter) CloseTicket(ctx interface{}, ticketID interface{}, userID interface{}, isAdmin interface{}) *MockTicketUsecase_CloseTicket_Call {
	return &MockTicketUsecase_CloseTicket_Call{Call: _e.mock.On("CloseTicket", ctx, ticketID, userID, isAdmin)}
}

func (_c *MockTicketUsecase_CloseTicket_Call) Run(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool)) *MockTicketUsecase_CloseTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_CloseTicket_Call) Return(closeTicketResponse *ticket.CloseTicketResponse, err error) *MockTicketUsecase_CloseTicket_Call {
	_c.Call.Return(closeTicketResponse, err)
	return _c
}

func (_c *MockTicketUsecase_CloseTicket_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool) (*ticket.CloseTicketResponse, error)) *MockTicketUsecase_CloseTicket_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTicket provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) CreateTicket(ctx context.Context, userID uint64, req ticket.CreateTicketRequest) (*ticket.TicketResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 *ticket.TicketResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, ticket.CreateTicketRequest) (*ticket.TicketResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, ticket.CreateTicketRequest) *ticket.TicketResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.TicketResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, ticket.CreateTicketRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockTicketUsecase_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - req ticket.CreateTicketRequest
func (_e *MockTicketUsecase_Expecter) CreateTicket(ctx interface{}, userID interface{}, req interface{}) *MockTicketUsecase_CreateTicket_Call {
	return &MockTicketUsecase_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, userID, req)}
}

func (_c *MockTicketUsecase_CreateTicket_Call) Run(run func(ctx context.Context, userID uint64, req ticket.CreateTicketRequest)) *MockTicketUsecase_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 ticket.CreateTicketRequest
		if args[2] != nil {
			arg2 = args[2].(ticket.CreateTicketRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_CreateTicket_Call) Return(ticketResponse *ticket.TicketResponse, err error) *MockTicketUsecase_CreateTicket_Call {
	_c.Call.Return(ticketResponse, err)
	return _c
}

func (_c *MockTicketUsecase_CreateTicket_Call) RunAndReturn(run func(ctx context.Context, userID uint64, req ticket.CreateTicketRequest) (*ticket.TicketResponse, error)) *MockTicketUsecase_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTickets provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetAllTickets(ctx context.Context) ([]*ticket.AdminTicketListItemResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTickets")
	}

	var r0 []*ticket.AdminTicketListItemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*ticket.AdminTicketListItemResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*ticket.AdminTicketListItemResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ticket.AdminTicketListItemResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_GetAllTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTickets'
type MockTicketUsecase_GetAllTickets_Call struct {
	*mock.Call
}

// GetAllTickets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketUsecase_Expecter) GetAllTickets(ctx interface{}) *MockTicketUsecase_GetAllTickets_Call {
	return &MockTicketUsecase_GetAllTickets_Call{Call: _e.mock.On("GetAllTickets", ctx)}
}

func (_c *MockTicketUsecase_GetAllTickets_Call) Run(run func(ctx context.Context)) *MockTicketUsecase_GetAllTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetAllTickets_Call) Return(adminTicketListItemResponses []*ticket.AdminTicketListItemResponse, err error) *MockTicketUsecase_GetAllTickets_Call {
	_c.Call.Return(adminTicketListItemResponses, err)
	return _c
}

func (_c *MockTicketUsecase_GetAllTickets_Call) RunAndReturn(run func(ctx context.Context) ([]*ticket.AdminTicketListItemResponse, error)) *MockTicketUsecase_GetAllTickets_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketDetail provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetTicketDetail(ctx context.Context, ticketID uint64) (*ticket.AdminTicketDetailResponse, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetTicketDetail")
	}

	var r0 *ticket.AdminTicketDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*ticket.AdminTicketDetailResponse, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *ticket.AdminTicketDetailResponse); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.AdminTicketDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_GetTicketDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketDetail'
type MockTicketUsecase_GetTicketDetail_Call struct {
	*mock.Call
}

// GetTicketDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketUsecase_Expecter) GetTicketDetail(ctx interface{}, ticketID interface{}) *MockTicketUsecase_GetTicketDetail_Call {
	return &MockTicketUsecase_GetTicketDetail_Call{Call: _e.mock.On("GetTicketDetail", ctx, ticketID)}
}

func (_c *MockTicketUsecase_GetTicketDetail_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketUsecase_GetTicketDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetTicketDetail_Call) Return(adminTicketDetailResponse *ticket.AdminTicketDetailResponse, err error) *MockTicketUsecase_GetTicketDetail_Call {
	_c.Call.Return(adminTicketDetailResponse, err)
	return _c
}

func (_c *MockTicketUsecase_GetTicketDetail_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) (*ticket.AdminTicketDetailResponse, error)) *MockTicketUsecase_GetTicketDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketFileURL provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetTicketFileURL(ctx context.Context, ticketID uint64) (*ticket.FileURLResponse, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetTicketFileURL")
	}

	var r0 *ticket.FileURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*ticket.FileURLResponse, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *ticket.FileURLResponse); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.FileURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_GetTicketFileURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketFileURL'
type MockTicketUsecase_GetTicketFileURL_Call struct {
	*mock.Call
}

// GetTicketFileURL is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketUsecase_Expecter) GetTicketFileURL(ctx interface{}, ticketID interface{}) *MockTicketUsecase_GetTicketFileURL_Call {
	return &MockTicketUsecase_GetTicketFileURL_Call{Call: _e.mock.On("GetTicketFileURL", ctx, ticketID)}
}

func (_c *MockTicketUsecase_GetTicketFileURL_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketUsecase_GetTicketFileURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetTicketFileURL_Call) Return(fileURLResponse *ticket.FileURLResponse, err error) *MockTicketUsecase_GetTicketFileURL_Call {
	_c.Call.Return(fileURLResponse, err)
	return _c
}

func (_c *MockTicketUsecase_GetTicketFileURL_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) (*ticket.FileURLResponse, error)) *MockTicketUsecase_GetTicketFileURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketMessages provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetTicketMessages(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool) ([]*ticket.MessageResponse, error) {
	ret := _mock.Called(ctx, ticketID, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetTicketMessages")
	}

	var r0 []*ticket.MessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) ([]*ticket.MessageResponse, error)); ok {
		return returnFunc(ctx, ticketID, userID, isAdmin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) []*ticket.MessageResponse); ok {
		r0 = returnFunc(ctx, ticketID, userID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ticket.MessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, bool) error); ok {
		r1 = returnFunc(ctx, ticketID, userID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_GetTicketMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketMessages'
type MockTicketUsecase_GetTicketMessages_Call struct {
	*mock.Call
}

// GetTicketMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
//   - userID uint64
//   - isAdmin bool
func (_e *MockTicketUsecase_Expecter) GetTicketMessages(ctx interface{}, ticketID interface{}, userID interface{}, isAdmin interface{}) *MockTicketUsecase_GetTicketMessages_Call {
	return &MockTicketUsecase_GetTicketMessages_Call{Call: _e.mock.On("GetTicketMessages", ctx, ticketID, userID, isAdmin)}
}

func (_c *MockTicketUsecase_GetTicketMessages_Call) Run(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool)) *MockTicketUsecase_GetTicketMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetTicketMessages_Call) Return(messageResponses []*ticket.MessageResponse, err error) *MockTicketUsecase_GetTicketMessages_Call {
	_c.Call.Return(messageResponses, err)
	return _c
}

func (_c *MockTicketUsecase_GetTicketMessages_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool) ([]*ticket.MessageResponse, error)) *MockTicketUsecase_GetTicketMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadURL provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetUploadURL(ctx context.Context, userID uint64, fileExtension string) (string, string, error) {
	ret := _mock.Called(ctx, userID, fileExtension)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadURL")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (string, string, error)); ok {
		return returnFunc(ctx, userID, fileExtension)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) string); ok {
		r0 = returnFunc(ctx, userID, fileExtension)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) string); ok {
		r1 = returnFunc(ctx, userID, fileExtension)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64, string) error); ok {
		r2 = returnFunc(ctx, userID, fileExtension)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTicketUsecase_GetUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadURL'
type MockTicketUsecase_GetUploadURL_Call struct {
	*mock.Call
}

// GetUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - fileExtension string
func (_e *MockTicketUsecase_Expecter) GetUploadURL(ctx interface{}, userID interface{}, fileExtension interface{}) *MockTicketUsecase_GetUploadURL_Call {
	return &MockTicketUsecase_GetUploadURL_Call{Call: _e.mock.On("GetUploadURL", ctx, userID, fileExtension)}
}

func (_c *MockTicketUsecase_GetUploadURL_Call) Run(run func(ctx context.Context, userID uint64, fileExtension string)) *MockTicketUsecase_GetUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetUploadURL_Call) Return(s string, s1 string, err error) *MockTicketUsecase_GetUploadURL_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockTicketUsecase_GetUploadURL_Call) RunAndReturn(run func(ctx context.Context, userID uint64, fileExtension string) (string, string, error)) *MockTicketUsecase_GetUploadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTickets provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) GetUserTickets(ctx context.Context, userID uint64) ([]*ticket.TicketListItemResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTickets")
	}

	var r0 []*ticket.TicketListItemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*ticket.TicketListItemResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*ticket.TicketListItemResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ticket.TicketListItemResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_GetUserTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTickets'
type MockTicketUsecase_GetUserTickets_Call struct {
	*mock.Call
}

// GetUserTickets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockTicketUsecase_Expecter) GetUserTickets(ctx interface{}, userID interface{}) *MockTicketUsecase_GetUserTickets_Call {
	return &MockTicketUsecase_GetUserTickets_Call{Call: _e.mock.On("GetUserTickets", ctx, userID)}
}

func (_c *MockTicketUsecase_GetUserTickets_Call) Run(run func(ctx context.Context, userID uint64)) *MockTicketUsecase_GetUserTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_GetUserTickets_Call) Return(ticketListItemResponses []*ticket.TicketListItemResponse, err error) *MockTicketUsecase_GetUserTickets_Call {
	_c.Call.Return(ticketListItemResponses, err)
	return _c
}

func (_c *MockTicketUsecase_GetUserTickets_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]*ticket.TicketListItemResponse, error)) *MockTicketUsecase_GetUserTickets_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockTicketUsecase
func (_mock *MockTicketUsecase) SendMessage(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool, req ticket.SendMessageRequest) (*ticket.MessageResponse, error) {
	ret := _mock.Called(ctx, ticketID, userID, isAdmin, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *ticket.MessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool, ticket.SendMessageRequest) (*ticket.MessageResponse, error)); ok {
		return returnFunc(ctx, ticketID, userID, isAdmin, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool, ticket.SendMessageRequest) *ticket.MessageResponse); ok {
		r0 = returnFunc(ctx, ticketID, userID, isAdmin, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.MessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, bool, ticket.SendMessageRequest) error); ok {
		r1 = returnFunc(ctx, ticketID, userID, isAdmin, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketUsecase_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockTicketUsecase_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
//   - userID uint64
//   - isAdmin bool
//   - req ticket.SendMessageRequest
func (_e *MockTicketUsecase_Expecter) SendMessage(ctx interface{}, ticketID interface{}, userID interface{}, isAdmin interface{}, req interface{}) *MockTicketUsecase_SendMessage_Call {
	return &MockTicketUsecase_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, ticketID, userID, isAdmin, req)}
}

func (_c *MockTicketUsecase_SendMessage_Call) Run(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool, req ticket.SendMessageRequest)) *MockTicketUsecase_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 ticket.SendMessageRequest
		if args[4] != nil {
			arg4 = args[4].(ticket.SendMessageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTicketUsecase_SendMessage_Call) Return(messageResponse *ticket.MessageResponse, err error) *MockTicketUsecase_SendMessage_Call {
	_c.Call.Return(messageResponse, err)
	return _c
}

func (_c *MockTicketUsecase_SendMessage_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64, userID uint64, isAdmin bool, req ticket.SendMessageRequest) (*ticket.MessageResponse, error)) *MockTicketUsecase_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
