// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/enum"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Create(ctx context.Context, ticket *entity.Ticket) error {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Ticket) error); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *entity.Ticket
func (_e *MockTicketRepository_Expecter) Create(ctx interface{}, ticket interface{}) *MockTicketRepository_Create_Call {
	return &MockTicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, ticket)}
}

func (_c *MockTicketRepository_Create_Call) Run(run func(ctx context.Context, ticket *entity.Ticket)) *MockTicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Ticket
		if args[1] != nil {
			arg1 = args[1].(*entity.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Create_Call) Return(err error) *MockTicketRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ticket *entity.Ticket) error) *MockTicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) CreateMessage(ctx context.Context, message *entity.TicketMessage) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TicketMessage) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockTicketRepository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *entity.TicketMessage
func (_e *MockTicketRepository_Expecter) CreateMessage(ctx interface{}, message interface{}) *MockTicketRepository_CreateMessage_Call {
	return &MockTicketRepository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, message)}
}

func (_c *MockTicketRepository_CreateMessage_Call) Run(run func(ctx context.Context, message *entity.TicketMessage)) *MockTicketRepository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TicketMessage
		if args[1] != nil {
			arg1 = args[1].(*entity.TicketMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_CreateMessage_Call) Return(err error) *MockTicketRepository_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, message *entity.TicketMessage) error) *MockTicketRepository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetAll(ctx context.Context) ([]*entity.Ticket, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Ticket, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Ticket); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTicketRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketRepository_Expecter) GetAll(ctx interface{}) *MockTicketRepository_GetAll_Call {
	return &MockTicketRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTicketRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTicketRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetAll_Call) Return(tickets []*entity.Ticket, err error) *MockTicketRepository_GetAll_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Ticket, error)) *MockTicketRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWithUsers provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetAllWithUsers(ctx context.Context) ([]*entity.Ticket, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithUsers")
	}

	var r0 []*entity.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Ticket, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Ticket); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetAllWithUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWithUsers'
type MockTicketRepository_GetAllWithUsers_Call struct {
	*mock.Call
}

// GetAllWithUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketRepository_Expecter) GetAllWithUsers(ctx interface{}) *MockTicketRepository_GetAllWithUsers_Call {
	return &MockTicketRepository_GetAllWithUsers_Call{Call: _e.mock.On("GetAllWithUsers", ctx)}
}

func (_c *MockTicketRepository_GetAllWithUsers_Call) Run(run func(ctx context.Context)) *MockTicketRepository_GetAllWithUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetAllWithUsers_Call) Return(tickets []*entity.Ticket, err error) *MockTicketRepository_GetAllWithUsers_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepository_GetAllWithUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Ticket, error)) *MockTicketRepository_GetAllWithUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetByID(ctx context.Context, ticketID uint64) (*entity.Ticket, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Ticket, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Ticket); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTicketRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketRepository_Expecter) GetByID(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetByID_Call {
	return &MockTicketRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetByID_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) Return(ticket *entity.Ticket, err error) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) (*entity.Ticket, error)) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithUser provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetByIDWithUser(ctx context.Context, ticketID uint64) (*entity.Ticket, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithUser")
	}

	var r0 *entity.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Ticket, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Ticket); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetByIDWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithUser'
type MockTicketRepository_GetByIDWithUser_Call struct {
	*mock.Call
}

// GetByIDWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketRepository_Expecter) GetByIDWithUser(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetByIDWithUser_Call {
	return &MockTicketRepository_GetByIDWithUser_Call{Call: _e.mock.On("GetByIDWithUser", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetByIDWithUser_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketRepository_GetByIDWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetByIDWithUser_Call) Return(ticket *entity.Ticket, err error) *MockTicketRepository_GetByIDWithUser_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_GetByIDWithUser_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) (*entity.Ticket, error)) *MockTicketRepository_GetByIDWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetByUserID(ctx context.Context, userID uint64) ([]*entity.Ticket, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*entity.Ticket, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*entity.Ticket); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockTicketRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockTicketRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockTicketRepository_GetByUserID_Call {
	return &MockTicketRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockTicketRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *MockTicketRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetByUserID_Call) Return(tickets []*entity.Ticket, err error) *MockTicketRepository_GetByUserID_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]*entity.Ticket, error)) *MockTicketRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastMessageByTicketID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetLastMessageByTicketID(ctx context.Context, ticketID uint64) (*entity.TicketMessage, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastMessageByTicketID")
	}

	var r0 *entity.TicketMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.TicketMessage, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.TicketMessage); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TicketMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetLastMessageByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMessageByTicketID'
type MockTicketRepository_GetLastMessageByTicketID_Call struct {
	*mock.Call
}

// GetLastMessageByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketRepository_Expecter) GetLastMessageByTicketID(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetLastMessageByTicketID_Call {
	return &MockTicketRepository_GetLastMessageByTicketID_Call{Call: _e.mock.On("GetLastMessageByTicketID", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetLastMessageByTicketID_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketRepository_GetLastMessageByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetLastMessageByTicketID_Call) Return(ticketMessage *entity.TicketMessage, err error) *MockTicketRepository_GetLastMessageByTicketID_Call {
	_c.Call.Return(ticketMessage, err)
	return _c
}

func (_c *MockTicketRepository_GetLastMessageByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) (*entity.TicketMessage, error)) *MockTicketRepository_GetLastMessageByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesByTicketID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) GetMessagesByTicketID(ctx context.Context, ticketID uint64) ([]*entity.TicketMessage, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByTicketID")
	}

	var r0 []*entity.TicketMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*entity.TicketMessage, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*entity.TicketMessage); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TicketMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_GetMessagesByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesByTicketID'
type MockTicketRepository_GetMessagesByTicketID_Call struct {
	*mock.Call
}

// GetMessagesByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
func (_e *MockTicketRepository_Expecter) GetMessagesByTicketID(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetMessagesByTicketID_Call {
	return &MockTicketRepository_GetMessagesByTicketID_Call{Call: _e.mock.On("GetMessagesByTicketID", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetMessagesByTicketID_Call) Run(run func(ctx context.Context, ticketID uint64)) *MockTicketRepository_GetMessagesByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_GetMessagesByTicketID_Call) Return(ticketMessages []*entity.TicketMessage, err error) *MockTicketRepository_GetMessagesByTicketID_Call {
	_c.Call.Return(ticketMessages, err)
	return _c
}

func (_c *MockTicketRepository_GetMessagesByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64) ([]*entity.TicketMessage, error)) *MockTicketRepository_GetMessagesByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Update(ctx context.Context, ticket *entity.Ticket) error {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Ticket) error); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTicketRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *entity.Ticket
func (_e *MockTicketRepository_Expecter) Update(ctx interface{}, ticket interface{}) *MockTicketRepository_Update_Call {
	return &MockTicketRepository_Update_Call{Call: _e.mock.On("Update", ctx, ticket)}
}

func (_c *MockTicketRepository_Update_Call) Run(run func(ctx context.Context, ticket *entity.Ticket)) *MockTicketRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Ticket
		if args[1] != nil {
			arg1 = args[1].(*entity.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Update_Call) Return(err error) *MockTicketRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ticket *entity.Ticket) error) *MockTicketRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) UpdateStatus(ctx context.Context, ticketID uint64, status enum.TicketStatus) error {
	ret := _mock.Called(ctx, ticketID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, enum.TicketStatus) error); ok {
		r0 = returnFunc(ctx, ticketID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTicketRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uint64
//   - status enum.TicketStatus
func (_e *MockTicketRepository_Expecter) UpdateStatus(ctx interface{}, ticketID interface{}, status interface{}) *MockTicketRepository_UpdateStatus_Call {
	return &MockTicketRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, ticketID, status)}
}

func (_c *MockTicketRepository_UpdateStatus_Call) Run(run func(ctx context.Context, ticketID uint64, status enum.TicketStatus)) *MockTicketRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 enum.TicketStatus
		if args[2] != nil {
			arg2 = args[2].(enum.TicketStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketRepository_UpdateStatus_Call) Return(err error) *MockTicketRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, ticketID uint64, status enum.TicketStatus) error) *MockTicketRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
