// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranslatorInstance creates a new instance of MockTranslatorInstance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslatorInstance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslatorInstance {
	mock := &MockTranslatorInstance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslatorInstance is an autogenerated mock type for the TranslatorInstance type
type MockTranslatorInstance struct {
	mock.Mock
}

type MockTranslatorInstance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslatorInstance) EXPECT() *MockTranslatorInstance_Expecter {
	return &MockTranslatorInstance_Expecter{mock: &_m.Mock}
}

// Locale provides a mock function for the type MockTranslatorInstance
func (_mock *MockTranslatorInstance) Locale() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Locale")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTranslatorInstance_Locale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Locale'
type MockTranslatorInstance_Locale_Call struct {
	*mock.Call
}

// Locale is a helper method to define mock.On call
func (_e *MockTranslatorInstance_Expecter) Locale() *MockTranslatorInstance_Locale_Call {
	return &MockTranslatorInstance_Locale_Call{Call: _e.mock.On("Locale")}
}

func (_c *MockTranslatorInstance_Locale_Call) Run(run func()) *MockTranslatorInstance_Locale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTranslatorInstance_Locale_Call) Return(s string) *MockTranslatorInstance_Locale_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTranslatorInstance_Locale_Call) RunAndReturn(run func() string) *MockTranslatorInstance_Locale_Call {
	_c.Call.Return(run)
	return _c
}

// Translate provides a mock function for the type MockTranslatorInstance
func (_mock *MockTranslatorInstance) Translate(key string, params ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(key, params)
	} else {
		tmpRet = _mock.Called(key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return returnFunc(key, params...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = returnFunc(key, params...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(key, params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslatorInstance_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslatorInstance_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - key string
//   - params ...string
func (_e *MockTranslatorInstance_Expecter) Translate(key interface{}, params ...interface{}) *MockTranslatorInstance_Translate_Call {
	return &MockTranslatorInstance_Translate_Call{Call: _e.mock.On("Translate",
		append([]interface{}{key}, params...)...)}
}

func (_c *MockTranslatorInstance_Translate_Call) Run(run func(key string, params ...string)) *MockTranslatorInstance_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTranslatorInstance_Translate_Call) Return(s string, err error) *MockTranslatorInstance_Translate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTranslatorInstance_Translate_Call) RunAndReturn(run func(key string, params ...string) (string, error)) *MockTranslatorInstance_Translate_Call {
	_c.Call.Return(run)
	return _c
}
