// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/entity"
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(ctx context.Context, transaction *entity.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *entity.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, transaction interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, transaction *entity.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entity.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, transaction *entity.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByID(ctx context.Context, transactionID uint64) (*entity.Transaction, error) {
	ret := _mock.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.Transaction, error)); ok {
		return returnFunc(ctx, transactionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.Transaction); ok {
		r0 = returnFunc(ctx, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uint64
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, transactionID interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, transactionID)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, transactionID uint64)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(transaction *entity.Transaction, err error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, transactionID uint64) (*entity.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProfileID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByProfileID(ctx context.Context, profileID uint64, pagination repository.TransactionPagination) (*repository.TransactionPaginatedResult, error) {
	ret := _mock.Called(ctx, profileID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetByProfileID")
	}

	var r0 *repository.TransactionPaginatedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, repository.TransactionPagination) (*repository.TransactionPaginatedResult, error)); ok {
		return returnFunc(ctx, profileID, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, repository.TransactionPagination) *repository.TransactionPaginatedResult); ok {
		r0 = returnFunc(ctx, profileID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.TransactionPaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, repository.TransactionPagination) error); ok {
		r1 = returnFunc(ctx, profileID, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProfileID'
type MockTransactionRepository_GetByProfileID_Call struct {
	*mock.Call
}

// GetByProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
//   - pagination repository.TransactionPagination
func (_e *MockTransactionRepository_Expecter) GetByProfileID(ctx interface{}, profileID interface{}, pagination interface{}) *MockTransactionRepository_GetByProfileID_Call {
	return &MockTransactionRepository_GetByProfileID_Call{Call: _e.mock.On("GetByProfileID", ctx, profileID, pagination)}
}

func (_c *MockTransactionRepository_GetByProfileID_Call) Run(run func(ctx context.Context, profileID uint64, pagination repository.TransactionPagination)) *MockTransactionRepository_GetByProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 repository.TransactionPagination
		if args[2] != nil {
			arg2 = args[2].(repository.TransactionPagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByProfileID_Call) Return(transactionPaginatedResult *repository.TransactionPaginatedResult, err error) *MockTransactionRepository_GetByProfileID_Call {
	_c.Call.Return(transactionPaginatedResult, err)
	return _c
}

func (_c *MockTransactionRepository_GetByProfileID_Call) RunAndReturn(run func(ctx context.Context, profileID uint64, pagination repository.TransactionPagination) (*repository.TransactionPaginatedResult, error)) *MockTransactionRepository_GetByProfileID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletSummary provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetWalletSummary(ctx context.Context, profileID uint64) (*repository.WalletSummary, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletSummary")
	}

	var r0 *repository.WalletSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*repository.WalletSummary, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *repository.WalletSummary); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.WalletSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetWalletSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletSummary'
type MockTransactionRepository_GetWalletSummary_Call struct {
	*mock.Call
}

// GetWalletSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockTransactionRepository_Expecter) GetWalletSummary(ctx interface{}, profileID interface{}) *MockTransactionRepository_GetWalletSummary_Call {
	return &MockTransactionRepository_GetWalletSummary_Call{Call: _e.mock.On("GetWalletSummary", ctx, profileID)}
}

func (_c *MockTransactionRepository_GetWalletSummary_Call) Run(run func(ctx context.Context, profileID uint64)) *MockTransactionRepository_GetWalletSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetWalletSummary_Call) Return(walletSummary *repository.WalletSummary, err error) *MockTransactionRepository_GetWalletSummary_Call {
	_c.Call.Return(walletSummary, err)
	return _c
}

func (_c *MockTransactionRepository_GetWalletSummary_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (*repository.WalletSummary, error)) *MockTransactionRepository_GetWalletSummary_Call {
	_c.Call.Return(run)
	return _c
}
