// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Barbod-Biometrics/Backend/gateway/internal/domain/localization"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// GetTranslator provides a mock function for the type MockTranslator
func (_mock *MockTranslator) GetTranslator(locale string) localization.TranslatorInstance {
	ret := _mock.Called(locale)

	if len(ret) == 0 {
		panic("no return value specified for GetTranslator")
	}

	var r0 localization.TranslatorInstance
	if returnFunc, ok := ret.Get(0).(func(string) localization.TranslatorInstance); ok {
		r0 = returnFunc(locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(localization.TranslatorInstance)
		}
	}
	return r0
}

// MockTranslator_GetTranslator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTranslator'
type MockTranslator_GetTranslator_Call struct {
	*mock.Call
}

// GetTranslator is a helper method to define mock.On call
//   - locale string
func (_e *MockTranslator_Expecter) GetTranslator(locale interface{}) *MockTranslator_GetTranslator_Call {
	return &MockTranslator_GetTranslator_Call{Call: _e.mock.On("GetTranslator", locale)}
}

func (_c *MockTranslator_GetTranslator_Call) Run(run func(locale string)) *MockTranslator_GetTranslator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_GetTranslator_Call) Return(translatorInstance localization.TranslatorInstance) *MockTranslator_GetTranslator_Call {
	_c.Call.Return(translatorInstance)
	return _c
}

func (_c *MockTranslator_GetTranslator_Call) RunAndReturn(run func(locale string) localization.TranslatorInstance) *MockTranslator_GetTranslator_Call {
	_c.Call.Return(run)
	return _c
}
