// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionUsecase creates a new instance of MockTransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionUsecase {
	mock := &MockTransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type MockTransactionUsecase struct {
	mock.Mock
}

type MockTransactionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionUsecase) EXPECT() *MockTransactionUsecase_Expecter {
	return &MockTransactionUsecase_Expecter{mock: &_m.Mock}
}

// GetUsageSummary provides a mock function for the type MockTransactionUsecase
func (_mock *MockTransactionUsecase) GetUsageSummary(ctx context.Context, profileID uint64) (*profile.UsageSummaryResponse, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageSummary")
	}

	var r0 *profile.UsageSummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*profile.UsageSummaryResponse, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *profile.UsageSummaryResponse); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.UsageSummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionUsecase_GetUsageSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsageSummary'
type MockTransactionUsecase_GetUsageSummary_Call struct {
	*mock.Call
}

// GetUsageSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uint64
func (_e *MockTransactionUsecase_Expecter) GetUsageSummary(ctx interface{}, profileID interface{}) *MockTransactionUsecase_GetUsageSummary_Call {
	return &MockTransactionUsecase_GetUsageSummary_Call{Call: _e.mock.On("GetUsageSummary", ctx, profileID)}
}

func (_c *MockTransactionUsecase_GetUsageSummary_Call) Run(run func(ctx context.Context, profileID uint64)) *MockTransactionUsecase_GetUsageSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionUsecase_GetUsageSummary_Call) Return(usageSummaryResponse *profile.UsageSummaryResponse, err error) *MockTransactionUsecase_GetUsageSummary_Call {
	_c.Call.Return(usageSummaryResponse, err)
	return _c
}

func (_c *MockTransactionUsecase_GetUsageSummary_Call) RunAndReturn(run func(ctx context.Context, profileID uint64) (*profile.UsageSummaryResponse, error)) *MockTransactionUsecase_GetUsageSummary_Call {
	_c.Call.Return(run)
	return _c
}
