// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// GetUserByID provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) GetUserByID(ctx context.Context, userID uint64) (*user.UserInfoResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *user.UserInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*user.UserInfoResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *user.UserInfoResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserUsecase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockUserUsecase_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserUsecase_GetUserByID_Call {
	return &MockUserUsecase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserUsecase_GetUserByID_Call) Run(run func(ctx context.Context, userID uint64)) *MockUserUsecase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUsecase_GetUserByID_Call) Return(userInfoResponse *user.UserInfoResponse, err error) *MockUserUsecase_GetUserByID_Call {
	_c.Call.Return(userInfoResponse, err)
	return _c
}

func (_c *MockUserUsecase_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*user.UserInfoResponse, error)) *MockUserUsecase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) UpdateProfile(ctx context.Context, profileInfo user.UpdateProfileRequest) (*user.UserInfoResponse, error) {
	ret := _mock.Called(ctx, profileInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *user.UserInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UpdateProfileRequest) (*user.UserInfoResponse, error)); ok {
		return returnFunc(ctx, profileInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UpdateProfileRequest) *user.UserInfoResponse); ok {
		r0 = returnFunc(ctx, profileInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, profileInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserUsecase_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profileInfo user.UpdateProfileRequest
func (_e *MockUserUsecase_Expecter) UpdateProfile(ctx interface{}, profileInfo interface{}) *MockUserUsecase_UpdateProfile_Call {
	return &MockUserUsecase_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profileInfo)}
}

func (_c *MockUserUsecase_UpdateProfile_Call) Run(run func(ctx context.Context, profileInfo user.UpdateProfileRequest)) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UpdateProfileRequest
		if args[1] != nil {
			arg1 = args[1].(user.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUsecase_UpdateProfile_Call) Return(userInfoResponse *user.UserInfoResponse, err error) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Return(userInfoResponse, err)
	return _c
}

func (_c *MockUserUsecase_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, profileInfo user.UpdateProfileRequest) (*user.UserInfoResponse, error)) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
