// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Barbod-Biometrics/Backend/gateway/internal/application/dto/wallet"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletUsecase creates a new instance of MockWalletUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletUsecase {
	mock := &MockWalletUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletUsecase is an autogenerated mock type for the WalletUsecase type
type MockWalletUsecase struct {
	mock.Mock
}

type MockWalletUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletUsecase) EXPECT() *MockWalletUsecase_Expecter {
	return &MockWalletUsecase_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockWalletUsecase
func (_mock *MockWalletUsecase) Deposit(ctx context.Context, userID uint64, profileID uint64, req wallet.DepositRequest) (*wallet.DepositResponse, error) {
	ret := _mock.Called(ctx, userID, profileID, req)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *wallet.DepositResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, wallet.DepositRequest) (*wallet.DepositResponse, error)); ok {
		return returnFunc(ctx, userID, profileID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, wallet.DepositRequest) *wallet.DepositResponse); ok {
		r0 = returnFunc(ctx, userID, profileID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.DepositResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, wallet.DepositRequest) error); ok {
		r1 = returnFunc(ctx, userID, profileID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletUsecase_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockWalletUsecase_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
//   - req wallet.DepositRequest
func (_e *MockWalletUsecase_Expecter) Deposit(ctx interface{}, userID interface{}, profileID interface{}, req interface{}) *MockWalletUsecase_Deposit_Call {
	return &MockWalletUsecase_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, profileID, req)}
}

func (_c *MockWalletUsecase_Deposit_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64, req wallet.DepositRequest)) *MockWalletUsecase_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 wallet.DepositRequest
		if args[3] != nil {
			arg3 = args[3].(wallet.DepositRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWalletUsecase_Deposit_Call) Return(depositResponse *wallet.DepositResponse, err error) *MockWalletUsecase_Deposit_Call {
	_c.Call.Return(depositResponse, err)
	return _c
}

func (_c *MockWalletUsecase_Deposit_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64, req wallet.DepositRequest) (*wallet.DepositResponse, error)) *MockWalletUsecase_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactions provides a mock function for the type MockWalletUsecase
func (_mock *MockWalletUsecase) GetTransactions(ctx context.Context, userID uint64, profileID uint64, page int, pageSize int) (*wallet.TransactionsResponse, error) {
	ret := _mock.Called(ctx, userID, profileID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 *wallet.TransactionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, int, int) (*wallet.TransactionsResponse, error)); ok {
		return returnFunc(ctx, userID, profileID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, int, int) *wallet.TransactionsResponse); ok {
		r0 = returnFunc(ctx, userID, profileID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.TransactionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, int, int) error); ok {
		r1 = returnFunc(ctx, userID, profileID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletUsecase_GetTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactions'
type MockWalletUsecase_GetTransactions_Call struct {
	*mock.Call
}

// GetTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
//   - page int
//   - pageSize int
func (_e *MockWalletUsecase_Expecter) GetTransactions(ctx interface{}, userID interface{}, profileID interface{}, page interface{}, pageSize interface{}) *MockWalletUsecase_GetTransactions_Call {
	return &MockWalletUsecase_GetTransactions_Call{Call: _e.mock.On("GetTransactions", ctx, userID, profileID, page, pageSize)}
}

func (_c *MockWalletUsecase_GetTransactions_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64, page int, pageSize int)) *MockWalletUsecase_GetTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWalletUsecase_GetTransactions_Call) Return(transactionsResponse *wallet.TransactionsResponse, err error) *MockWalletUsecase_GetTransactions_Call {
	_c.Call.Return(transactionsResponse, err)
	return _c
}

func (_c *MockWalletUsecase_GetTransactions_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64, page int, pageSize int) (*wallet.TransactionsResponse, error)) *MockWalletUsecase_GetTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletSummary provides a mock function for the type MockWalletUsecase
func (_mock *MockWalletUsecase) GetWalletSummary(ctx context.Context, userID uint64, profileID uint64) (*wallet.WalletSummaryResponse, error) {
	ret := _mock.Called(ctx, userID, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletSummary")
	}

	var r0 *wallet.WalletSummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*wallet.WalletSummaryResponse, error)); ok {
		return returnFunc(ctx, userID, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) *wallet.WalletSummaryResponse); ok {
		r0 = returnFunc(ctx, userID, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletSummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletUsecase_GetWalletSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletSummary'
type MockWalletUsecase_GetWalletSummary_Call struct {
	*mock.Call
}

// GetWalletSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - profileID uint64
func (_e *MockWalletUsecase_Expecter) GetWalletSummary(ctx interface{}, userID interface{}, profileID interface{}) *MockWalletUsecase_GetWalletSummary_Call {
	return &MockWalletUsecase_GetWalletSummary_Call{Call: _e.mock.On("GetWalletSummary", ctx, userID, profileID)}
}

func (_c *MockWalletUsecase_GetWalletSummary_Call) Run(run func(ctx context.Context, userID uint64, profileID uint64)) *MockWalletUsecase_GetWalletSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWalletUsecase_GetWalletSummary_Call) Return(walletSummaryResponse *wallet.WalletSummaryResponse, err error) *MockWalletUsecase_GetWalletSummary_Call {
	_c.Call.Return(walletSummaryResponse, err)
	return _c
}

func (_c *MockWalletUsecase_GetWalletSummary_Call) RunAndReturn(run func(ctx context.Context, userID uint64, profileID uint64) (*wallet.WalletSummaryResponse, error)) *MockWalletUsecase_GetWalletSummary_Call {
	_c.Call.Return(run)
	return _c
}
